<script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<div id="gmapmodal" class="modal hide fade" style="width: 700px; margin-left: -350px;">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Confirma la localización de tu Comercio</h3>
    </div>
    <div class="modal-body" style="max-height: none; padding:0 15px 0 15px;">
        <table style="width: 100%; background-color: transparent;">
            <tr>
                <td colspan="2">
                    <p id="smallfont" style="margin: 5px; font-size: 0.9em;">
                    Recuerda que es muy importante que tu localización sea la correcta. Con ella tus clientes podrán encontrarte.
                    Si el mapa no te indica tu dirección correctamente intenta cambiando alguno de los datos que cargaste para el comercio.
                    Si aún así sigues sin encontrar tu dirección avísanos por email y nosotros lo resolveremos. 
                    </p>        
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <div id="gmap">
                        <img id="map" src="" alt="Tu localización">
                    </div>            
                </td>
            </tr>
        </table>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="btnCancelLoc" onclick="jQuery('.close').click();">Cancelar</a>
        <a href="#" class="btn btn-primary" id="btnConfirm" onclick="ConfirmLocation();">Confirmar Localización</a>
    </div>
</div>
<script type="text/javascript">
var _confirmed = false;
function SearchLocation(){
    var street = document.getElementById("street").value.toString();
    var number = document.getElementById("number").value.toString();    
    var city = document.getElementById("city").options[document.getElementById("city").selectedIndex].text;
    var province = document.getElementById("province").options[document.getElementById("province").selectedIndex].text;
    var country = "Argentina";
    var localaddress = street+" "+number+","+city+","+province+","+country;
    localaddress = encodeURI(localaddress);
    var localaddress2 = street+" "+number+","+city+","+province+","+country;
    localaddress2 = localaddress2.replace(" ","+");
    //localaddress2 = encodeURI(localaddress2);
    var zoom="16";
    var size="350x280";
    var sensor="false";
    
    var urlGoogleMaps = "";
    
    var geocoder = new google.maps.Geocoder();
    
    //convert location into longitude and latitude
    geocoder.geocode({
        address: localaddress2
    }, function(locResult) {
        var lat1 = locResult[0].geometry.location.lat();
        var lng1 = locResult[0].geometry.location.lng();
        jQuery("#latitude").val(lat1);
        jQuery("#longitude").val(lng1);
    });
    
    urlGoogleMaps = "http://maps.google.com/maps/api/staticmap?center="+localaddress
                            +"&zoom="+zoom
                            +"&size="+size
                            +"&markers=icon:http://dev.promosalpaso.com/images/pap_location.png|" + localaddress //document.getElementById("latitude").value + "," + document.getElementById("longitude").value     // label:S%7C11211%7C11206%7C11222" 
                            +"&sensor="+sensor; 
     
    document.getElementById("map").src = urlGoogleMaps;
}

function ConfirmLocation(){
    jQuery("#lat").val(jQuery("#latitude").val());
    jQuery("#lng").val(jQuery("#longitude").val());
    jQuery("#gmapmodal").modal("hide")
    jQuery("#localization").focus();    
    _confirmed = true;
}

function ShowGoogleLocalizator(){
    if(jQuery("#street").val() == "" || jQuery("#number").val() == "" ){
        bootbox.alert("La calle y el número son datos requeridos");
        return false;
    }
    else{
        jQuery("#locationModal").click();
    }
    
//    SearchLocation();
    //$("gmapmodal").modal("show");
}

function CancelLocation(){
    if(!_confirmed){
        jQuery("#lat").val("");
        jQuery("#lng").val("");
        jQuery("#latitude").val("");
        jQuery("#longitude").val("");
        _confirmed = false;
    }
}

jQuery(document).ready(function(){
    jQuery("#gmapmodal").on('show', function(){
        SearchLocation();
    })

    jQuery("#gmapmodal").on("hidden", function(){
        CancelLocation();        
    })
})


</script>