<div id="editUserInfo" class="modal hide fade" style="width:380px">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Editar datos de Usuario</h3>
    </div>
    <div class="container form-horizontal">
        <div class="row-fluid">
            <div id="div_nombre" class="control-group">
                <label class="control-label required" for="ui_name">Nombre/Razón Social:</label>
                <div class="controls">
                    <input id="ui_name" type="text" value="" required>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div id="div_cuit" class="control-group">
                <label class="control-label" for="ui_cuit">Cuit:</label>
                <div class="controls">
                    <input id="ui_cuit" type="text" value="" required>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div id="div_pass" class="control-group">
                <label class="control-label" for="ui_pass">Nueva Contraseña:</label>
                <div class="controls">
                    <input id="ui_newpass" type="password" value="">
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div id="div_newpass" class="control-group">
                <label class="control-label" for="ui_newpass">Confirmar Contraseña:</label>
                <div class="controls">
                    <input id="ui_newpassconf" type="password" value="">
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div id="div_nombre" class="control-group">
                <label class="control-label required" for="ui_name">Contraseña Actual:</label>
                <div class="controls">
                    <input id="ui_pass" type="password" value="" required>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="offset1">
                <input type="button" class="btn btn-primary" id="btn_accountinfocancel" value="Cancelar" onclick="jQuery('button.close').click();"></input>
                <input type="button" class="btn btn-primary" id="btn_accountinfo" value="Guardar" onclick="editUserInfo();"></input>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function editUserInfo(){
        if(jQuery('#ui_newpass').val() != jQuery('#ui_newpassconf').val()){
            alert("La nueva contraseña y su confirmación no son idénticas.")
            return false;
        }
        var json_data = {
                'user_id':jQuery('#user').val(),
                'name':jQuery('#ui_name').val(),
                'cuit':jQuery('#ui_cuit').val(),
                'string1':jQuery('#ui_newpass').val(),
                'string2':jQuery('#ui_newpassconf').val(),
                'string3':jQuery('#ui_pass').val(),
        };
        $.ajax({
                url: _baseServUri + 'edituserinfo',
                dataType: 'jsonp',
                data: {"data":json_data},
                jsonp: 'jsoncallback',
                contentType: "application/json; charset=utf-8",
                timeout: 5000,
                success: function(data, status){
                        if(data.length == 0)
                            alert(data);
                },
                error: function(jqXHR, textStatus, errorThrown){
                    alert(textStatus);    
                }
        });
            
        jQuery("#payHidden").click();
    }
    
    jQuery(document).ready(function(){
        jQuery("#ui_name").val(jQuery("#user_name").val());    
        jQuery("#ui_cuit").val(jQuery("#user_cuit").val()); 
        
    })
    
</script>