<?php 
//$this->headScript()->appendScript("/scripts/jquery-latest.js");
//$this->headScript()->appendScript("/scripts/jquery.cookie.js");
//$this->headScript()->appendScript("/scripts/jquery.treeview.js");
if(isset($this->errorMessage)){
        echo $this->errorMessage;
    }
$this->form->setAction($this->url());
//echo $this->form;
$form = $this->form;

?>
<!--<script type="text/javascript" src="/scripts/jquery-latest.js"></script>
<script type="text/javascript" src="/scripts/jquery.cookie.js"></script>
<script type="text/javascript" src="/scripts/jquery.treeview.js"></script>
<link rel="stylesheet" type="text/css" href="/skins/default/css/jquery.treeview.css"></link>
-->

<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="http://jquery.bassistance.de/treeview/lib/jquery.cookie.js" type="text/javascript"></script>
<link rel="stylesheet" href="http://jquery.bassistance.de/treeview/jquery.treeview.css" type="text/css" />
<style type="text/css">
    #treeViewCategorias{
        border: 1px solid;
    }
</style>
<script type="text/javascript" src="http://jquery.bassistance.de/treeview/jquery.treeview.js"></script>
    <div align="center">
        <table width="95%">
            <tr>
                <td align="center" valign="middle" height="75px">
                    <div style="background-image: url(/images/backend/tit-categorias.png); background-repeat:no-repeat; background-position: center; height: 50px;">&nbsp;</div>
                </td>
            </tr>
            <tr>
                <td>
                    <div id="view-content">
                        <p>Selecciona tus categorías. Es importante establecer las mismas para que tus potenciales clientes puedan buscar rapidamente tus promociones.</p>
                        <p>Esta selecciòn aplica a nivel de Comercio. Oséa que todas las promociones que publiques estarán asociadas a estas categorías.</p>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <?php echo $this->form; ?>
                </td>
            </tr>
        </table>
    </div>
<script type="text/javascript">
$(document).ready(function(){
    $("#tree").treeview({
        persist: "cookie",
        cookieId: "treeview-black"
    });
});
</script>
