<?php 
    $messages = $this->form->getMessages();
    $this->form->setAction($this->url());
    $form = $this->form;
?>
<!--<script type="text/javascript" src="/scripts/jquery-latest.js"></script>
<script type="text/javascript" src="/scripts/jquery.cookie.js"></script>
<script type="text/javascript" src="/scripts/jquery.treeview.js"></script>
<link rel="stylesheet" type="text/css" href="/skins/default/css/jquery.treeview.css"></link>
-->
<!--<script src="http://code.jquery.com/jquery-latest.js"></script>-->
<!--<link rel="stylesheet" href="http://jquery.bassistance.de/treeview/jquery.treeview.css" type="text/css" />-->
<link rel="stylesheet" href="/skins/default/css/jquery.treeview.css" type="text/css" />
<script  type="text/javascript" src="/scripts/jquery.cookie.js"></script>
<script type="text/javascript" src="/scripts/jquery.treeview.js"></script>
<style type="text/css">
    #treeViewCategorias{
        border: 3px solid;
    }
</style>
<div class="row-fluid pagination-centered">
    <div class="row">
        <div class="span4 offset4" id="titulo" align="center">
            <h1>Mis Categorías</h1>
        </div>
    </div>
    <?php echo $this->errorMessage($this->form, $messages); ?>
    <hr class="hr-subtitle"/>
    <?php echo $this->partial("index/_alert.phtml"); ?>
</div>

    <div class="row pagination-centered">
        <div class="span10">
        <p>Selecciona tus categorías. Es importante establecer las mismas para que tus potenciales clientes puedan encontrar rapidamente tus promociones.</p>
        <p>Esta selecciòn aplica a nivel de Comercio. Oséa que todas las promociones que publiques estarán asociadas a estas categorías.</p>
        </div>
        <div class="span1">
            <img src="/images/backend/goto-help.png" width="32px" onclick="loadHelp('Selección de Categorías', 'tabs-reg-4');" title="Ayuda de Categorías" style="float: right;"/>
        </div>
    </div>
    <div class="row pagination-centered">
        <table width="100%" style="background-color: transparent;">
            <tr>
                <td align="center">
                    <?php echo $this->form; ?>        
                </td>
            </tr>
        </table>
    </div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery("#tree").treeview({
        persist: "cookie",
        cookieId: "treeview-black"
    });
    jQuery("#div_message").hide();
    jQuery("form table").css("background-color", "transparent");
    if($("#popUpMessage").val() != ""){
            showPopUpModalMessage("Mis Categorías", $("#popUpMessage").val());
            $("#popUpMessage").val("");
    }
});

function someCategoryChecked(){
    var someChecked = jQuery("input[type=checkbox]:checked").val()?true:false;
    if(!someChecked){
        showMessage("error", "Debes seleccionar al menos una categoría para tu comercio.");
        return false;
    }    
}
</script>
<?php 
    echo $this->partial("index/_contextual-help.phtml"); 
?>