<?php 
//$this->headScript()->appendScript("/scripts/jquery-latest.js");
//$this->headScript()->appendScript("/scripts/jquery.cookie.js");
//$this->headScript()->appendScript("/scripts/jquery.treeview.js");
echo $this->form;
?>
<!--<script type="text/javascript" src="/scripts/jquery-latest.js"></script>
<script type="text/javascript" src="/scripts/jquery.cookie.js"></script>
<script type="text/javascript" src="/scripts/jquery.treeview.js"></script>
<link rel="stylesheet" type="text/css" href="/skins/default/css/jquery.treeview.css"></link>
-->
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="http://jquery.bassistance.de/treeview/lib/jquery.cookie.js" type="text/javascript"></script>
<link rel="stylesheet" href="http://jquery.bassistance.de/treeview/jquery.treeview.css" type="text/css" />
<script type="text/javascript" src="http://jquery.bassistance.de/treeview/jquery.treeview.js"></script>

<script type="text/javascript">
$(document).ready(function(){
    $("#tree").treeview({
        persist: "cookie",
        cookieId: "treeview-black"
    });
});
</script>