<?php  //$this->headScript()->appendScript($this->baseUrl().'/scripts/regions.js');
       //echo $this->headScript();
 ?>
 <script type="text/javascript">
function loadCities()
{
        var selectedValue = document.getElementById('province').options[document.getElementById('province').selectedIndex].value;
        var myAjax = new Ajax.Request(
        "<?=$this->url(array('controller'=>'backendAjax','action'=>'getCities'))?>",
            {
                method:'get',
                parameters: {province_id: selectedValue},
                onSuccess: FillForm
        });
 
}

function FillForm(data)
{       var select = document.getElementById("city");
        select.options.length = 0;
        var cities = eval('(' + data.responseText + ')');
        for (var i = 0; i < cities.length; i++){
            select.options[select.options.length] = new Option(cities[i].name, cities[i].city_id); 
        } 
}

function clickFile(){
        document.getElementById("file").click();
}
function sub(obj){
    var file = obj.value;
    var fileName = file.split("\\");
    document.getElementById("yourFile").innerHTML = fileName[fileName.length-1];
}
</script>
<?php
    if(isset($this->errorMessage)){
        echo $this->errorMessage;
    }
    $this->form->setAction($this->url());
    echo $this->form;
    echo $this->partial("branch/_localizator.phtml"); 
?>


