<?php
    $messages = $this->form->getMessages();
?>
<script type="text/javascript" src="/scripts/prototype.js"></script>
<script type="text/javascript">
function loadCities()
{
        clearCoord();
        var selectedValue = document.getElementById('province').options[document.getElementById('province').selectedIndex].value;
        var myAjax = new Ajax.Request(
        "<?=$this->url(array('controller'=>'Backendajax','action'=>'getcities'))?>",
            {
                method:'get',
                parameters: {province_id: selectedValue},
                onSuccess: FillForm
        });
 
}

function FillForm(data)
{
        var select = document.getElementById("city");
        select.options.length = 0;
        var cities = eval('(' + data.responseText + ')');
        for (var i = 0; i < cities.length; i++){
            select.options[select.options.length] = new Option(cities[i].name, cities[i].city_id); 
        } 
}

function clickFile(){
        document.getElementById("filebranch").click();
}
function sub(obj){
    var file = obj.value;
    var fileName = file.split("\\");
    document.getElementById("yourFile").innerHTML = "<p>" + fileName[fileName.length-1] + "</p>";
}

function clearCoord(){
    document.getElementById("lat").value = "";
    document.getElementById("latitude").value = "";
    document.getElementById("lng").value = "";
    document.getElementById("longitude").value = "";
}

</script>
<?php
    $this->form->setAction($this->url());
    //echo $this->form;
    $form = $this->form;
?>
<style type="text/css">
legend{
    font-size: small;
}
</style>
<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype="multipart/form-data">
    <div align="center">
        <table width="95%">
            <tr>
                <td colspan="2" align="center" valign="middle" height="65px">
                    <div style="background-image: url(/images/backend/tit-misdatos.png); background-repeat:no-repeat; background-position: center; height: 50px; width: 100%">&nbsp;</div>
                    <hr/>
                    <?php echo $this->errorMessage($this->form, $messages); ?>
                </td>
            </tr>
            <tr>
                <td width="100%" colspan="2">
                    <fieldset>
                        <legend><b>Domicilio</b></legend>
                        <table width="100%">
                            <tr>
                                <td><?php echo $form->name->renderLabel(); ?></td>
                                <td colspan="3"><?php echo $form->name->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->street->renderLabel(); ?></td>
                                <td colspan="3"><?php echo $form->street->renderViewHelper(); ?></td>
                                <td><?php echo $form->number->renderLabel(); ?></td>
                                <td><?php echo $form->number->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->local->renderLabel(); ?></td>
                                <td><?php echo $form->local->renderViewHelper(); ?></td>
                                <td><?php echo $form->phone->renderLabel(); ?></td>
                                <td><?php echo $form->phone->renderViewHelper(); ?></td>
                                <td align="right"><?php echo $form->zipcode->renderLabel(); ?></td>
                                <td><?php echo $form->zipcode->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->province->renderLabel(); ?></td>
                                <td><?php echo $form->province->renderViewHelper(); ?></td>
                                <td><?php echo $form->city->renderLabel(); ?></td>
                                <td><?php echo $form->city->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->website->renderLabel(); ?></td>
                                <td colspan="2"><?php echo $form->website->renderViewHelper(); ?></td>
                                <td><?php echo $form->email->renderLabel(); ?></td>
                                <td colspan="2"><?php echo $form->email->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td colspan="6">
                                    <div class="ui-widget-content ui-corner-all" style="padding-left: 5px;">
                                    <p>Luego de que hayas ingresado los datos requeridos de tu comercio (nombre del comercio, calle, número, localidad y provincia) debes ubicarlo geograficamente
                                    pulsando el botón "Localizarme". Al hacerlo el sistema te mosrtará un mapa indicando el lugar en donde se encuentra tu comercio.</p>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                               <td><?php echo $form->lat->renderLabel(); ?></td>
                               <td><?php echo $form->lat->renderViewHelper(); ?></td>
                               <td><?php echo $form->lng->renderLabel(); ?></td>
                               <td><?php echo $form->lng->renderViewHelper(); ?></td>
                               <td align="right" colspan="2" valign="top"><?php echo $form->localization->renderViewHelper(); ?></td> 
                            </tr>
                        </table>
                    </fieldset>
                </td>
            </tr>
            <tr>
                <td valign="top">
                    <fieldset>
                        <legend align="left"><b>Imagen Comercio</b></legend>
                        <table width="100%">
                            <tr>
                                <td align="center" valign="top" rowspan="2" style="padding-right: 10px">
                                    <?php echo $form->logo->renderViewHelper(); ?>
                                </td>
                                <td colspan="2">
                                    <div class="ui-widget-content ui-corner-all" style="padding-left: 5px">
                                    <p>La imagen del Comercio es de suma importancia. Aparte de ser tu presentación en tu página de negocio, será 
                                    la imagen por defecto de todas aquellas promociones sin foto que publiques.</p>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td><div id='yourFile'><p>&nbsp;</p></div></td>
                                <td align="right" valign="top">
                                    <?php
                                        echo $form->fakefile->renderViewHelper(); 
                                    ?>
                                </td>
                            </tr>
                        </table>    
                    </fieldset>
                </td>
            </tr>
            <tr>
                <td valign="top" align="right" colspan="2">
                    <?php
                        echo $form->cancel->renderViewHelper(); 
                        echo $form->save->renderViewHelper(); 
                    ?></td>
                        
            </tr>
        </table>
    </div>
    <div>
        <?php
            echo $form->user;
            echo $form->branch_id;
            echo $form->branch_order;
            echo $form->latitude;
            echo $form->longitude;
            echo $form->filebranch;
            
        ?>
    </div>
</form>
<?php 
    echo $this->partial("branch/_localizator.phtml"); 
?>