<?php
    $messages = $this->form->getMessages();
?>
<script type="text/javascript" src="/scripts/prototype.js"></script>
<script type="text/javascript">
function loadCities()
{
        clearCoord();
        var selectedValue = document.getElementById('province').options[document.getElementById('province').selectedIndex].value;
        var myAjax = new Ajax.Request(
        "<?=$this->url(array('controller'=>'Backendajax','action'=>'getCities'))?>",
            {
                method:'get',
                parameters: {province_id: selectedValue},
                onSuccess: FillForm
        });
 
}

function FillForm(data)
{
        var select = document.getElementById("city");
        select.options.length = 0;
        var cities = eval('(' + data.responseText + ')');
        for (var i = 0; i < cities.length; i++){
            select.options[select.options.length] = new Option(cities[i].name, cities[i].city_id); 
        } 
}

function clickFile(){
        document.getElementById("filebranch").click();
}
function sub(obj){
    var file = obj.value;
    var fileName = file.split("\\");
    document.getElementById("yourFile").innerHTML = "<p>" + fileName[fileName.length-1] + "</p>";
}

function clearCoord(){
    document.getElementById("lat").value = "";
    document.getElementById("latitude").value = "";
    document.getElementById("lng").value = "";
    document.getElementById("longitude").value = "";
}
</script>
<?php
    $this->form->setAction($this->url());
    $form = $this->form;
?>
<form id="content-form" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype="multipart/form-data" class="form-horizontal">
<div class="row-fluid">
    <div class="row">
        <div class="pagination-centered" id="titulo">
            <h1>Mis Datos</h1>
        </div>
    </div>
    <hr class="hr-subtitle"/>
    <?php echo $this->errorMessage($this->form, $messages); ?>
    <?php echo $this->partial("index/_alert.phtml"); ?>
    <div class="row-fluid">
        <div class="span12">
            <fieldset>
                <legend><h4>Domicilio</h4></legend>
                <div class="row-fluid">
                    <div class="span6">
                        <div class="control-group">
                            <?php echo $form->name->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->name->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                    <div class="span6">
                        <div class="control-group">
                            <?php echo $form->phone->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->phone->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <div class="control-group">
                            <?php echo $form->street->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->street->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                    <div class="span6">
                        <div class="control-group">
                            <?php echo $form->number->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->number->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <div class="control-group">
                            <?php echo $form->local->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->local->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                    <div class="span6">
                        <div class="control-group">
                            <?php echo $form->zipcode->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->zipcode->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <div class="control-group">
                            <?php echo $form->province->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->province->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                    <div class="span6">
                        <div class="control-group">
                            <?php echo $form->city->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->city->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <div class="control-group">
                            <?php echo $form->website->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->website->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                    <div class="span6">
                        <div class="control-group">
                            <?php echo $form->email->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->email->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12 well">
                        <p>Luego de que hayas ingresado los datos requeridos de tu comercio (nombre del comercio, calle, número, localidad y provincia) debes ubicarlo geograficamente
                        pulsando el botón "Localizarme". Al hacerlo el sistema te mosrtará un mapa indicando el lugar en donde se encuentra tu comercio.</p>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span4">
                        <div class="control-group">
                            <?php echo $form->lat->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->lat->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="control-group">
                            <?php echo $form->lng->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->lng->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                    <div class="span4" style="text-align: right;">
                        <button type="button" class="btn btn-small" onclick="ShowGoogleLocalizator();"><i class="icon-map-marker"></i> Localizarme</button>
                        <button id="locationModal" type="button" data-toggle="modal" data-target="#gmapmodal" style="display: none;"></button>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <fieldset>
                    <legend align="left"><h4>Imagen Comercio</h4></legend>
                    <div class="row-fuid">
                        <table style="border-collapse: collapse; border-bottom-color: white;">
                            <tr>
                                <td width="75%">
                                    <div class="well">
                                        <p>La imagen del Comercio es de suma importancia. Aparte de ser tu presentación en tu página de negocio, será 
                                        la imagen por defecto de todas aquellas promociones sin foto que publiques.</p>
                                    </div>
                                </td>
                                <td width="15%" align="center">
                                    <div>
                                        <?php echo $form->logo->renderViewHelper(); ?>
                                        <div id='yourFile'><small>&nbsp;</small>
                                    </div>        
                                </td>
                                <td width="10%">
                                    <button id="fakefile" class="btn btn-small" onclick="clickFile();" type="button" name="fakefile"><i class="icon-upload"></i> Cargar Imagen</button>
                                </td>
                            </tr>
                        </table>
                    </div>
                </fieldset>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span3 offset9" style="text-align: right;">
            <?php echo $form->cancel->renderViewHelper(); 
                  echo $form->save->renderViewHelper(); ?>
        </div>
    </div>
    <div>
        <?php
            echo $form->user;
            echo $form->branch_id;
            echo $form->branch_order;
            echo $form->latitude;
            echo $form->longitude;
            echo $form->filebranch;
            
        ?>
    </div>
</div>
<script type="text/javascript">
    jQuery('#content-form').validate({
        rules: {
          name: {
            minlength: 5,
            required: true
          },
          street: {
            minlength: 4,
            required: true
          },
          number: {
            minlength: 1,
            required: true
          },
          email: {
            required: true,
            email: true
          },
          lat: {
            minlength: 4,
            required: true
          },
          lng: {
            minlength: 4,
            required: true
          },
        },
        highlight: function(element) {
            jQuery(element).closest('.control-group').removeClass('success').addClass('error');
            
        },
        success: function(element) {
            jQuery(element).text('OK!').addClass('valid')
            jQuery(element).closest('.control-group').removeClass('error').addClass('success');
        }
      });
      
      jQuery('#local').tooltip({
        placement: 'right',
        title: 'Este campo puede contener cualquier información extra para que los clientes puedan localizar tu comercio. Por ejemplo el número de local dentro de una determinada galería.',
      });
      
      
</script>    
</form>
<?php 
    echo $this->partial("branch/_localizator.phtml"); 
?>