<?php
    if(isset($this->errorMessage)){
        echo $this->errorMessage;
    }
?>
<script type="text/javascript">
function loadCities()
{
        var selectedValue = document.getElementById('province').options[document.getElementById('province').selectedIndex].value;
        var myAjax = new Ajax.Request(
        "<?=$this->url(array('controller'=>'backendAjax','action'=>'getCities'))?>",
            {
                method:'get',
                parameters: {province_id: selectedValue},
                onSuccess: FillForm
        });
 
}

function FillForm(data)
{
        var select = document.getElementById("city");
        select.options.length = 0;
        var cities = eval('(' + data.responseText + ')');
        for (var i = 0; i < cities.length; i++){
            select.options[select.options.length] = new Option(cities[i].name, cities[i].city_id); 
        } 
}
</script>
<?php
    $this->form->setAction($this->url());
    //echo $this->form;
    $form = $this->form;
?>
<style type="text/css">
legend{
    font-size: small;
}
</style>
<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
    <div align="center">
        <table width="95%">
            <tr>
                <td colspan="2" align="center" valign="middle" height="75px">
                    <div style="background-image: url(/images/backend/tit-misdatos.png); background-repeat:no-repeat; background-position: center; height: 50px; width: 100%">&nbsp;</div>
                </td>
            </tr>
            <tr>
                <td width="70%" rowspan="2">
                    <fieldset>
                        <legend><b>Domicilio</b></legend>
                        <table width="100%" style= 'border:1px solid black;'>
                            <tr>
                                <td><?php echo $form->name->renderLabel(); ?></td>
                                <td><?php echo $form->name->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->street->renderLabel(); ?></td>
                                <td><?php echo $form->street->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->number->renderLabel(); ?></td>
                                <td><?php echo $form->number->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->local->renderLabel(); ?></td>
                                <td><?php echo $form->local->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->phone->renderLabel(); ?></td>
                                <td><?php echo $form->phone->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->province->renderLabel(); ?></td>
                                <td><?php echo $form->province->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->city->renderLabel(); ?></td>
                                <td><?php echo $form->city->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->zipcode->renderLabel(); ?></td>
                                <td><?php echo $form->zipcode->renderViewHelper(); ?></td>
                            </tr>
                        </table>
                    </fieldset>
                    
                </td>
                <td valign="top">
                    <fieldset>
                        <legend align="left"><b>Imagen Comercio</b></legend>
                        <table width="100%">
                            <tr>
                                <td align="center"><?php echo $form->logo->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td align="center"><?php echo $form->fakefile->renderViewHelper(); ?></td>
                            </tr>
                        </table>    
                    </fieldset>
                </td>
            </tr>
            <tr>
                <td valign="top">
                    <fieldset>
                        <legend align="left"><b>Localización</b></legend>
                        <table width="100%">
                            <tr>
                                <td><?php echo $form->lat->renderLabel(); ?></td>
                                <td align="center"><?php echo $form->lat->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->lng->renderLabel(); ?></td>
                                <td align="center"><?php echo $form->lng->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td align="center"><?php echo $form->localization->renderViewHelper(); ?></td>
                            </tr>
                        </table>    
                    </fieldset>
                </td>
            </tr>
            
        </table>
    </div>
</form>
<?php 
    echo $this->partial("branch/_localizator.phtml"); 
?>
