<script type="text/javascript">
    function showTipoOperacion(){
        var operacion = $('#ddl_operacion').val();
        if(operacion == "T"){
            $('#div_banco_trans').show();
            $('#div_banco_dep').hide();
        }
        else{
            $('#div_banco_dep').show();
            $('#div_banco_trans').hide();    
        }
    }
    function showOtro(){
        var banco = $('#ddl_banco_orig').val();
        if(banco == 'otro')
            $('#div_otro_banco').show();
        else
            $('#div_otro_banco').hide();
    }
</script>
<div id="paymentInfo" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Informar pago por transferencia/depósito</h3>
    </div>
    <div class="container form-horizontal">
        <div class="row-fluid">
            <div id="div_desc_pago" class="control-group">
                <label class="control-label" for="txt_desc_pago">Período/s a pagar:</label>
                <div class="controls">
                    <input id="txt_desc_pago" value="" readonly="true">
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="control-group" id="div_tipo_tx">
                <label class="control-label" for="ddl_operacion">Tipo Operación:</label>
                <div class="controls">
                    <select id="ddl_operacion" onchange="showTipoOperacion();">
                        <option value="T">Transferencia</option>
                        <option value="D">Depósito</option>
                    </select>
                </div>
            </div>    
        </div>
        <div class="row-fluid">
            <div class="control-group" id="div_banco_trans">
                <label class="control-label" for="ddl_banco_orig">Banco:</label>
                <div class="controls">
                    <select id="ddl_banco_orig" onChange="showOtro();">
                        <option value="galicia">Galicia</option>
                        <option value="santander">Santander</option>
                        <option value="otro">Otro</option>
                    </select>
                </div>
            </div>    
        </div>
        <div class="row-fluid" id="div_otro_banco" style="display: none;">
            <div class="control-group">
                <label class="control-label" for="txt_otro_banco">Otro:</label>
                <div class="controls">
                    <input id="txt_otro_banco" value="">
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="control-group" id="div_banco_dep" style="display: none;">
                <label class="control-label" for="ddl_banco_dest">Cuenta destino:</label>
                <div class="controls">
                    <select id="ddl_banco_dest">
                        <option value="galicia">Galicia</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="control-group" id="div_nro_tx">
                <label class="control-label" for="txt_nro_tx">Nro transacción:</label>
                <div class="controls">
                    <input id="txt_nro_tx" type="text"/>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="control-group" id="div_fecha">
                <label class="control-label" for="txt_fecha">Fecha:</label>
                <div class="controls">
                    <input id="txt_fecha" type="text" readonly="true"/>
                </div>
            </div>
        </div>    
        <div class="row-fluid">
            <div class="control-group" id="div_monto">
                <label class="control-label" for="txt_monto">Monto:</label>
                <div class="controls">
                    <input id="txt_monto" type="text"/>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span2 pagination-right">
                <input type="button" class="btn btn-primary" id="btn_accountinfo" value="Imprimir Info" onclick="printAccountInfo();"></input>
            </div>
            <div class="span2 pagination-centered">
                <input type="button" class="btn btn-primary" id="btn_pay" value="Informar Pago" onclick="sendPayment();"></input>
            </div>
            <div class="span2">
                <input type="button" class="btn btn-primary" id="cancel" value="Cancelar" onclick="hidePaymentForm();"></input>
            </div>
        </div>
    </div>
    <input type="hidden" id="charges_ids" />
</div>

<script type="text/javascript">
    function hidePaymentForm(){
        jQuery("button.close").click();
    }
    
    function validatePaymentForm(){
        resp = true;
        if($('#ddl_operacion').val() == "T"){
            if($('#ddl_banco_orig').val() == "otro"){
                if($('#txt_otro_banco').val() == "" )
                    resp = false;
            }
        }
        if($('#txt_nro_tx').val() == "")
            resp = false;
        if($('#txt_monto').val() == "" )
            resp = false;
        if($('#txt_fecha').val() == "")
            resp = false;
        return resp;   
    }
    
    $(document).ready(function(){
       $("#txt_fecha").datepicker({
          showOn: 'both',
          buttonImage: '/images/calendar-icon.png',
          buttonImageOnly: true,
          changeYear: false,
          maxDate: 0,
          numberOfMonths: 1,
       });
       $("#txt_fecha" ).datepicker( "setDate", new Date() );
    });
    
    function printAccountInfo(){
        var periods = jQuery("#txt_desc_pago").val();
        var amount = jQuery("#txt_monto").val();
        window.open("payment/accountinfo/periods/"+periods+"/amount/"+amount, 'info', 'height=360,width=390,left=100,top=100,resizable=no,scrollbars=no,toolbar=no,status=no');
    }
</script>