    <script type="text/javascript" src='/scripts/jquery-1.8.2.js'></script>
    <style type="text/css">
        table{
            border-color: #666666;
            border-collapse: collapse;
            border-width: 2px;
            border-style: solid;
            border-width: medium;
            font-family: Arial, Helvetica, sans-serif;
            width: 375px;
        }
        
        td{
            padding: 5px;
        }
        
        #pap{
            font-size: 36px;
            font-weight: bold;
            color: #FF6A15;
        }
        
        .title{
            background: #666666;
            color: #FFFFFF;
            font-weight: bold;
        }
        .label{
            font-weight: bold;    
        }    
    </style>
    <table>
        <tr>
            <td><img src="/images/logo-promosalpaso70.png" alt="Promos al Paso" width="48px"/></td>
            <td><span id="pap">Promos al Paso</span></td>
        </tr>
        <tr>
            <td colspan="2" class="title">Datos de cuenta para transferencia/depósito</td>
        </tr>
    </table>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery(".subnav").remove();    
        });
    </script>
