<?php
    $messages = $this->errorMessage;
    $this->form->setAction($this->url());
    $form = $this->form;
?>
<script type="text/javascript" src='/scripts/grid.locale-es.js'></script>
<!--<script type="text/javascript" src='/scripts/jquery.jqGrid.min.js'></script>-->
<script type="text/javascript" src='/scripts/jquery.jqGrid.src.js'></script>
<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
<div class="row-fluid">
    <div class="row">
        <div class="pagination-centered" id="titulo">
            <h1>Mis Cargos</h1>
        </div>
    </div>
    <hr class="hr-subtitle"/>
    <?php echo $this->errorMessage($this->form, $messages); ?>
    <div class="row-fluid pagination-centered">
            <p>En esta sección encontrarás información acerca de tu historial de anuncios y también te permitirá ver, pagar o informar el pago de los cargos que adeudas.</p>
    </div>
    <div class="row-fluid">
        <div class="span3 pagination-right">
            <p>Selecciona el tipo de reporte:</p>
        </div>
        <div class="span6 ">
            <?php echo $form->reportType->renderViewHelper(); ?>
        </div>
        <div class="span2 pagination-right">
            <?php echo $form->search->renderViewHelper(); ?>
        </div>    
    </div>
    <div class="row-fluid">
        <div class="span8 offset2">
            <table width="100%"><tr><td align="center">
                <table id="list2"></table>
                <div id="pager2"></div>
            </td></tr></table>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span3 offset3">
            <button id="pay" type="button" data-toggle="modal" data-target="#paymentInfo" class="btn">Informar Pago por Transferencia/Depósito</button>
        </div>
        <div class="span3">
            <button id="payMP" type="button" class="btn" onclick="showMercadoPago();">Pagar por MercadoPago</button>
            <button id="payHiddenMP" type="button" data-toggle="modal" data-target="#div_MP" style="height: 0px; width: 0px;"></button>
        </div>
    </div>
    <div id="div_alert" class="alert alert-error" style="display: none;">
            <a class="close" onclick="closeMessage()">×</a>
            <h4 class="alert-heading">Atención!</h4>
            <p id="p_message"></p>
    </div>
    
</div>
<?php echo $form->data->renderViewHelper(); ?>
</form>
<script type="text/javascript">
    $(document).ready(function(){
        $("#pay").hide();
        $("#payHiddenMP").hide();
        $("#payMP").hide();
        $("#div_MP").hide();
        if($('input#data').val() != ""){
            getPayments();
        }         
    });
</script>
<?php 
    echo $this->partial("payment/_paymentInfo.phtml"); 
    echo $this->partial("payment/_frameMP.phtml"); 
?>