<?php
    $messages = $this->errorMessages;
    $this->form->setAction($this->url());
    $form = $this->form;
?>
<script type="text/javascript" src='/scripts/grid.locale-es.js'></script>
<!--<script type="text/javascript" src='/scripts/jquery.jqGrid.min.js'></script>-->
<script type="text/javascript" src='/scripts/jquery.jqGrid.src.js'></script>
<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
    <div class="row-fluid">
        <div class="row">
            <div class="pagination-centered" id="titulo">
                <h1>Mis Cargos</h1>
            </div>
        </div>
        <hr class="hr-subtitle"/>
        <?php echo $this->errorMessage($this->form, $messages); ?>
    </div>
    <div class="row-fluid pagination-centered">
        <div class="span11">
            <p>En esta sección encontrarás información acerca de tu historial de anuncios y también te permitirá ver, pagar o informar el pago de los cargos que adeudas.</p>
        </div>
        <div class="span1">
            <img src="/images/backend/goto-help.png" width="32px" onclick="loadHelp('Cargos del servicio', 'tabs-costos-2');" title="Ayuda de cargos del servicio" style="float: right;"/>    
        </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span3 well">
                <div class="row-fluid pagination-left">
                    <span>Selecciona el tipo de reporte:</span>
                </div>
                <div class="row-fluid ">
                    <?php echo $form->reportType->renderViewHelper(); ?>
                </div>
                <div class="row-fluid pagination-centered">
                    <?php echo $form->search->renderViewHelper(); ?>
                </div>
            </div>
            <div class="span9" style="height: 100%; min-height: 175px;">
                <?php echo $this->partial("index/_alert.phtml"); ?>
                <div class="row-fluid">
                    <table width="100%" style="background-color: #202328;"><tr><td align="center">
                        <table id="list2"></table>
                        <div id="pager2"></div>
                    </td></tr></table>
                </div>
                <div class="row-fluid pagination-centered">
                        <button id="pay" type="button" class="btn" onclick="showPaymentInfo();">Informar Pago por Transferencia/Depósito</button>
                        <button id="payHidden" type="button" style="display: none;" data-toggle="modal" data-target="#paymentInfo" class="btn"></button>
                        <button id="payMP" type="button" class="btn" onclick="showMercadoPago();">Pagar por MercadoPago</button>
                        <button id="payHiddenMP" type="button" data-toggle="modal" data-target="#div_MP" style="display: none;"></button>
                        <button id="payCash" type="button" class="btn" onclick="requestCashPayment();">Efectivo</button>
                    </div>
                </div>
            </div>
        </div>    
    </div>
    
    <div class="row-fluid">
        <div class="span8 offset2">
            
        </div>
    </div>
    
<?php echo $form->data->renderViewHelper(); ?>
<?php echo $form->popUpMessage->renderViewHelper(); ?>
<script type="text/javascript">
    $(document).ready(function(){
        $("#pay").hide();
        $("#payHiddenMP").hide();
        $("#payMP").hide();
        $("#div_MP").hide();
        $("#payCash").hide();
        $("#div_MP").hide();
        if($('input#data').val() != ""){
            getPayments();
        }
        
        if($("#popUpMessage").val() != ""){
            showPopUpModalMessage("Mi Cuenta", $("#popUpMessage").val());
        }         
    });
</script>
<?php 
     echo $this->partial("payment/_paymentInfo.phtml"); 
     echo $this->partial("payment/_frameMP.phtml"); 
?>
</form>
<?php echo $this->partial("index/_contextual-help.phtml");?>