<table style="width: 100%; background-color: transparent;">
    <tr>
        <td colspan="2" class="home-title-section" style="width: 100%;">AVISO</td>
    </tr>
    <tr>
        <td colspan="2" align="center" style="margin: 20px;">Por el momento no soportamos Internet Explorer, estamos trabajando en ello.</td>
    </tr>
    <tr>
        <td colspan="2" align="center" style="margin: 20px;">Por favor ingresa al gestor de promociones con Chrome o Firefox</td>
    </tr>
    <tr>
        <td align="right"><a href="https://www.google.com/intl/es/chrome/browser/?hl=es" target="_blank"><img style="height: 100px; margin: 20px;" src="/images/backend/chrome.png" alt="Google Chrome"/></a></td>
        <td align="left"><a href="http://www.mozilla.org/es-AR/firefox/new/" target="_blank"><img style="height: 100px; margin: 20px;" src="/images/backend/firefox.png" alt="Mozilla Firefox"/></a></td>
    </tr>
</table>