<table>
    <tr>
        <td colspan="2">AVISO</td>
    </tr>
    <tr>
        <td colspan="2">Por el momento no soportamos Internet Explorer, estamos trabajando en ello.</td>
    </tr>
    <tr>
        <td colspan="2">Por favor ingresa al gestor de promociones con Chrome o Firefox</td>
    </tr>
    <tr>
        <td><a href="https://www.google.com/intl/es/chrome/browser/?hl=es" target="_blank"><img style="height: 120px;" src="/images/backend/chrome.png" alt="Google Chrome"/></a></td>
        <td><a href="http://www.mozilla.org/es-AR/firefox/new/" target="_blank"><img style="height: 120px;" src="/images/backend/firefox.png" alt="Mozilla Firefox"/></a></td>
    </tr>
</table>