<div class="row">
    <div class="span6 offset3" id="titulo" align="center">
            <h1>Términos y Condiciones</h1>
    </div>
</div>
<hr class="hr-subtitle"/>

<h3>Términos y condiciones generales y particulares de anuncios Promos al Paso</h3>
<span>
1.El servicio de publicación de avisos de venta y/o promoción y/o publicidad de servicios y productos (en adelante el "Servicio o Producto") es ofrecido por Promos al Paso (en lo sucesivo “PAP”), en su carácter de responsable de la operación y explotación del sitio http:\\promosalpaso.com y http:\\promosalpaso.com.ar (de aquí en más el “Sitio”), a los anunciantes y/o usuarios (en adelante individualmente el “Usuario” y genéricamente los “Usuarios”) que accedan y se registren en el Sitio a fines de proceder con una o más publicaciones, con la condición de que acepten sin ninguna objeción todos y cada uno de los TSCC que se describen a continuación. Asimismo, debido a que ciertos contenidos que puedan ser accedidos a través del Sitio podrán estar alcanzados por normas específicas que reglamenten y complementen a los presentes TSCC, se recomienda a los Usuarios tomar conocimiento específico de ellas a través del sitio http:\\promosalpaso.com. 
</span>
<h5>2. ALCANCE DE LOS TSCC</h5>
<span>
Fuera de lo estipulado en la última parte del apartado precedente, los presentes TSCC y las normas que los complementan sólo serán aplicables a los servicios y contenidos prestados y/o accesibles directamente en el Sitio y no a aquellos a los que los Usuarios puedan acceder a través de un hipervínculo (link), una barra co-branded, y/o cualquier otra herramienta de navegación ubicada en el Sitio que los lleve a navegar un recurso diferente.
La probable aparición de dichos links en el Sitio no implica de modo alguno la asunción de garantía por parte de PAP sobre los productos, servicios o programas contenidos en ninguna página vinculada al Sitio por tales links. 
Declara PAP no haber revisado ninguna de las páginas a las que pueda llegar a accederse desde el Sitio y, en consecuencia, deslinda toda responsabilidad por el contenido de las mismas. En atención a ello, la utilización de los links para navegar hacia cualquier otra página queda al exclusivo criterio responsabilidad y riesgo de los Usuarios.
</span>
<h5>3. INGRESO Y PUBLICACIÓN DE CLASIFICADOS</h5>
<span>
A fin de publicar un aviso clasificado a través del Sitio, el Usuario deberá registrarse e ingresar de manera correcta todos los datos de su comercio, así como el texto, fotos y demás información del aviso que pretende publicar. El Usuario deberá aceptar la totalidad de las condiciones de contratación, como requisito previo al ingreso de los datos a publicar, ingresando al link ubicado en el sitio bajo la denominación de registración. 
PAP podrá realizar un control del mismo procediendo, entre otros criterios, a la revisión de su contenido e incluso a su remoción del Sitio si su contenido no se correspondiere con estos TSCC, en cuyo caso el Usuario perderá todo derecho a reclamar las sumas por él abonadas/adeudadas, sin derecho a reembolso de ninguna naturaleza.
Reconocen y aceptan los Usuarios que sólo podrán publicarse aquellos avisos cuyas características se encuentren contenidas en los nomencladores de marcas, modelos y versiones bajo los cuales opera el Sitio.
El Servicio es pago en aquellos casos en que el usuario opte por un plan que otorgue beneficios en comparación al aviso gratuito, por lo que el Usuario se obliga a pagar los precios establecidos por PAP, los que podrán ser cambiados por éste a su solo criterio.
Los distintos tipos de avisos vigentes y sus respectivos valores se encuentran disponibles en el proceso de publicación, y el usuario declara haber tomado debido conocimiento y conformidad  con ellos . 
</span>
<h5>4. PUBLICACIÓN EN EL SITIO WEB</h5>
<span>
4.1. Plazos de Publicación:<br/> 
Cumplidos los requisitos del apartado anterior, PAP publicará los avisos en el Sitio por el término de días que establezca el Cliente, según  se corresponda con la opción elegida por el usuario.  <br/>
4.2. Modificación y/o baja  de los avisos:<br/>
Los avisos podrán ser modificados o dado de baja  por los propios Usuarios a través de la edición de los anuncios, al que se accede con el usuario y contraseña con el que se registraron.
</span> 
<h5>5. CONDUCTA DE LOS USUARIOS</h5>
<span>
Queda expresamente prohibido a “Los Usuarios” utilizar el Servicio para:<br/>
(i) ofrecer o publicar material ilegal, difamatorio, obsceno, pornográfico, racista, discriminatorio, agraviante, injurioso o que afecte la privacidad de las personas; <br/>
(ii)- ofrecer o publicar fotografías, propias o de terceros, cuya imagen sea obscena, inmoral o contraria a las buenas costumbres; <br/>
(iii) - ofrecer o publicar material mediante la falsificación de su identidad; <br/>
(iv) ofrecer o publicar material en infracción a la ley, violar cualquier legislación aplicable local, federal, nacional o internacional; <br/>
(v)- ofrecer, publicar o crear una base de datos personales de terceros. <br/>
(vi) Publicar imágenes, fotografías, publicaciones, ideas, marcas, patentes, inventos, que no sean de su propiedad o que pertenezcan a terceras personas sean estas físicas o jurídicas  <br/>
El incumplimiento por parte de los Usuarios de cualquiera de las condiciones precedentes, implicará de inmediato la no publicación o baja del aviso en el Sitio, conforme lo estipulado en el apartado 9. 
</span>
<h5>6. CALIDAD DE LOS SERVICIOS Y PRODUCTOS PROMOCIONADOS</h5>
<span>>
El Sitio no pretende contener una lista exhaustiva de todos los productos del mercado y PAP  no manifiesta ni garantiza de modo alguno y por ende no asume responsabilidad de ninguna especie respecto a  que no existan otros productos en el mercado, incluso más convenientes, en precio o condiciones, como así tampoco que no existan otros productos que cumplan la misma función que los publicados en el Sitio. 
En consecuencia, sugiere firmemente PAP que la información brindada por el Sitio respecto de los productos publicados, sea objeto de una investigación independiente y propia de quien esté interesado en la misma, no asumiendo PAP ningún tipo de responsabilidad por la incorrección de la información, su desactualización o falsedad.
PAP no asume ninguna obligación respecto del Usuario y/o los visitantes del “Sitio” en general y se limita tan sólo a publicar en el Sitio en forma similar a aquella en que lo haría una guía telefónica o la sección clasificados de un periódico impreso, los datos de los Usuarios proveedores de productos o servicios que han solicitado tal publicación y en la forma en que tales datos han sido proporcionados por tales Usuarios.
 
PAP no resulta propietario de los productos y servicios que se publicitan, y por ende no garantiza en forma alguna dichos productos y servicios, ya sea respecto de su calidad, condiciones de entrega, prestación, precio, modalidades de pago, estado de conservación, como respecto de ningún otro aspecto, ni garantiza a los Usuarios y/o visitantes en general respecto de la existencia, crédito, capacidad, solvencia material y moral ni sobre ningún otro aspecto de los Usuarios proveedores de tales productos y servicios.
PAP no es pues productor, fabricante, importador, distribuidor, proveedor ni vendedor de los productos o servicios que se ofrecen. El contrato de compraventa de productos o la contratación de los servicios con sus proveedores se realiza fuera de la esfera de participación de PAP y sin su intervención, directamente entre el Usuario oferente y quien resulte comprador del producto o servicio por aquél ofrecido. Por tal virtud, PAP no otorga garantía de evicción ni por vicios ocultos o aparentes de los bienes publicados por el Usuario oferente y adquiridos por quien resulte comprador, ni se responsabiliza de ningún daño o perjuicio que pudiera sufrir el usuario o los visitantes del “Sitio” en los términos de la ley 24.240, su decreto reglamentario y modificatorias.
Asimismo, aceptan y reconocen los Usuarios que PAP no controla, ni supervisa, el cumplimiento de los requisitos legales para ofrecer y vender los productos o servicios, ni sobre la capacidad y legitimación de los Usuarios oferentes para promocionar, ofrecer y/o vender sus bienes o servicios. 
</span>
<h5>7. ESPACIO ASIGNADO EN EL SERVICIO</h5>
<span>
PAP tiene la libre facultad de establecer y modificar la cantidad de espacio mínimo y máximo de MB que el Usuario oferente puede utilizar, para publicar los avisos clasificados en el Sitio    
El usuario reconoce que PAP puede poner límites respecto al uso del Servicio, con inclusión, entre otras cosas, de la cantidad máxima de días que el Contenido será retenido por el Servicio, la cantidad y el tamaño máximo de los anuncios, los mensajes de email, o de todo otro Contenido que se puede transmitir o almacenar a través del Servicio, y la frecuencia con la cual el Usuario puede acceder al Servicio. El Usuario conviene en que PAP no es responsable de la eliminación o el fracaso en el almacenamiento de aquel Contenido que se conserva o que se transmite a través del Servicio. El Usuario entiende que PAP se reserva el derecho para, en todo momento, modificar o interrumpir el Servicio (o una parte de este) con o sin notificación, y que PAP no será responsable ante el Usuario ni ante un tercero por la modificación, la suspensión o la interrupción del Servicio .
El Usuario conviene en que PAP, a su entera y sola discreción, tiene el derecho (pero no la obligación) de eliminar o desactivar la cuenta del Usuario, de bloquear su dirección de email o IP, o bien de cualquier otra forma cancelar el acceso o el uso del Servicio (o parte de este) por parte del Usuario, en forma inmediata y sin notificación previa. Asimismo, PAP podrá quitar o descartar Contenido dentro el Servicio, por cualquier motivo, con inclusión, no restrictiva, del momento en que PAP considere que el Usuario actuó en forma contraria a la letra o el espíritu de las Condiciones. Sumado a ello, el Usuario conviene en que PAP no será responsable ante el Usuario mismo ni ante un tercero por la cancelación del acceso del Usuario al Servicio. Además, el Usuario conviene en no intentar usar el Servicio luego de la cancelación por parte de PAP. 
</span>
<h5>8. BASE DE DATOS</h5>
<span>
PAP se compromete a no ceder, vender, ni entregar a otras empresas o personas físicas, la información suministrada por los Usuarios. 
Los Usuarios aceptan por el hecho de registrarse como tales en el Sitio, el derecho de PAP de comunicarse con ellos en forma telefónica o vía electrónica; ello, hasta tanto los Usuarios hagan saber su decisión en contrario a La Voz del Interior S.A. por medio fehaciente. Esta autorización incluye la recepción de correos electrónicos, newsletter, alertas diarias, etc  .
</span>
<h5>9. PUBLICACION DE ANUNCIOS EN PROMOS AL PASO - PAGO DEL SERVICIO</h5>
<span>
A favor de todo aquel anunciante que contrate la publicación de anuncios implica la publicación del mismo tanto en el sitio web como en la aplicación mobile bajo un mismo coste.
El pago de los servicios podrá hacerse mediante el uso de tarjetas de crédito o débito, a través de la plataforma de MercadoPago (www.mercadopago.com), mediante depósito o transferencia bancaria. 
</span>
<h5>10. RESPONSABILIDAD</h5>
<span>
Los Usuarios resultan responsables de toda afirmación y/o expresión y/o acto celebrado con su nombre de usuario y contraseña.
Los Usuarios aceptan y reconocen que PAP no será responsable, contractual ni extracontractualmente, por ningún daño o perjuicio, directo o indirecto, derivado de la utilización del Servicio y/o la publicación de Avisos o su contenido.
</span>
<h5>11. INDEMNIDAD</h5>
<span>
Los Usuarios asumen total responsabilidad frente a PAP y a terceros por los daños y/o perjuicios de toda clase que se generen como consecuencia del uso del Servicio, debiendo indemnizar y mantener indemne a PAP y a terceros ante cualquier reclamo (incluyendo honorarios profesionales costos y costas) que pudiera corresponder en los supuestos indicados.
</span>
<h5>12. MODIFICACIÓN DEL SERVICIO O DE LOS TSCC</h5>
<span>
PAP se reserva el derecho a modificar el Servicio, los TSCC y las normas que los complementan, en cualquier momento y cuantas veces lo crea conveniente, sin necesidad de notificar en forma previa a los Usuarios. 
Queda entendido y así deberá ser interpretado en caso de conflicto que es obligación del Usuario revisar periódicamente las normas que reglamentan el Servicio.
Los Usuarios no podrán hacer responsable a PAP y/o a ningún tercero por la suspensión o terminación del Servicio, a excepción del cumplimiento de los servicios o productos publicados y pagados. 
</span>
<h5>13. LOS USUARIOS EXPRESAMENTE COMPRENDEN Y ESTÁN DE ACUERDO EN QUE:</h5>
<span>
a. La utilización del Servicio es a su solo riesgo; <br/>
b. PAP no garantiza que el Servicio sea el adecuado a sus necesidades;<br/>
c. El Servicio puede ser suspendido o interrumpido;<br/>
d. El Servicio puede contener errores;<br/>
e. PAP no será responsable por ningún daño o perjuicio, directo o indirecto, incluyendo, sin ningún tipo de limitación, daños producidos por la pérdida o deterioro de información;<br/>
f. Los Usuarios son los únicos responsables de los contenidos de la información que se publica a través del Servicio, frente a PAP y a terceras personas sean estas físicas o jurídicas. 
g. PAP se reserva el derecho a suspender, limitar y/o terminar el Servicio.<br/> 
h. El Servicio puede no siempre estar disponible debido a dificultades técnicas o fallas de Internet, o por cualquier otro motivo ajeno a PAP, motivo por el cual no podrá imputársele a PAP responsabilidad alguna.<br/>
i. El contenido de las distintas pantallas del Sitio junto con, y sin que se considere una limitación, sus programas, bases de datos, redes y archivos, son de propiedad de PAP. Su uso indebido así como su reproducción no autorizada podrá dar lugar a las acciones judiciales que correspondan.<br/>
j. La utilización del Servicio no podrá, en ningún supuesto, ser interpretada como una autorización y/o concesión de licencia para la utilización de los derechos intelectuales de La Voz y/o de un tercero.<br/>
k. La utilización de Internet en general y del Sitio en particular, implica la asunción de riesgos de potenciales daños al software y al hardware del Usuario. <br/>
Por tal motivo, el equipo terminal desde el cual acceda al Sitio el Usuario, estaría en condiciones de resultar atacado y dañado por la acción de hackers quienes podrían incluso acceder a la información contenida en el equipo terminal del Usuario, extraerla, sustraerla y/o dañarla.<br/>
l. Paralelamente, el intercambio de información a través de Internet tiene el riesgo de que tal información pueda ser captada por un tercero. PAP no se hace responsable de las consecuencias que pudiera acarrear al Usuario tal hipótesis.<br/>
m. PAP no guarda obligación alguna de conservar información que haya hecho disponible a los Usuarios, ni que le haya sido enviada por éstos últimos.<br/>
</span>
<h5>14. LEY APLICABLE Y TRIBUNAL COMPETENTE</h5>
<span>
Los presentes TSCC y las normas que lo complementan constituyen un acuerdo legal entre los Usuarios y PAP, al cual le serán aplicadas las leyes de la República Argentina, siendo competentes para cualquier controversia que pudiere llegar a suscitarse, los tribunales nacionales en lo comercial, con asiento en la Ciudad  de San Justo, provincia de Buenos Aires.
La utilización del Servicio está expresamente prohibida en toda jurisdicción en donde no puedan ser aplicadas las condiciones establecidas en los presentes TSCC.
Si los Usuarios utilizan el Servicio significa que han leído, entendido y acordado las normas antes expuestas. Si no están de acuerdo con ellas, deben abstenerse de hacer uso del servicio.
Toda notificación u otra comunicación que deba efectuarse bajo estos TSCC, deberá realizarse por escrito: (i) al Usuario: a la cuenta de correo electrónico por él ingresada o por carta documento dirigida al domicilio declarado en su ficha de registración o (ii) a PAP: a la cuenta de correo electrónico administración@promosalpaso.com o a PROMOS AL PASO, Avda Arturo Humberto Illia 3620 , San Justo – Provincia de Buenos Aires.
</span>