 <script>
    $(function() {
        $( "#accordion" ).accordion({
            collapsible: true,
            autoHeight: false,
            navigation: true, 
        });
        $( "#tabs-reg" ).tabs();
        $( "#tabs-promos" ).tabs();
        $( "#tabs-costos" ).tabs();
        
        $("#img-buscar-promos").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:357, zoomWindowWidth:500});
        $("#img-buscar-promos-detalle").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:357, zoomWindowWidth:500});
        $("#img-registracion").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:241, zoomWindowWidth:351});
        $("#img-branch").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:394, zoomWindowWidth:500});
        $("#img-categories").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:368, zoomWindowWidth:485});
        $("#img-index-promos").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:373, zoomWindowWidth:500});
        $("#img-portal-resumen-promos").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:249, zoomWindowWidth:414});
        $("#img-portal-grilla-promos").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:357, zoomWindowWidth:500});
        $("#img-portada-promo").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:318, zoomWindowWidth:500});
        $("#img-promo-mobile").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:500, zoomWindowWidth:461});
        $("#img-detalle-promo").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:397, zoomWindowWidth:500});
        $("#img-promo-costo").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:114, zoomWindowWidth:290});
        $("#img-promo-costo-total").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:420, zoomWindowWidth:500});
        $("#img-promos-cargos").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:301, zoomWindowWidth:500});
        $("#img-promo-costos-detalle").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:257, zoomWindowWidth:500});
        $("#img-mobile-promolist").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:531, zoomWindowWidth:367});
        $("#img-promos-ordenamiento").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:292, zoomWindowWidth:611});
        $("#img-promo-metodos-pago").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:384, zoomWindowWidth:500});
        $("#img-metodo-pago-transferencia").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:467, zoomWindowWidth:503});
        $("#img-pago-efectivo").elevateZoom({zoomWindowPosition: 10, zoomWindowHeight:148, zoomWindowWidth:390});
    });
</script>

<h3>¿Qué es Promos al Paso?</h3>
<p class="plain-text">bla bla bla bla</p>

<div id="accordion">
    <h3>Buscar promociones</h3>
    <div>
        <div id="buscar_promos">
            <div style="width: 75%; float: left;">
                <p class="plain-text">Promos al Paso fue creado pensando principalmente para darle a los usuario de dispositivos móbiles
                inteligentes (smart phones) la posibilidad de encontrar promociones que se encuentren cerca de donde la persona se encuentra
                situada.</p>
                <p class="plain-text">Pero Promos al Paso también te permite encontrar promociones en una localidad determinada por intermedio
                de cualquier computadora conectada a internet.</p>
                <p class="plain-text">Para ello en la página principal de Promos al Paso pulsa en el botón Buscar Promos en la barra superior.
                Esto te llevará a la página de búsqueda que te permitirá hacer búsqueda de promociones en las ciudades en la que se encuentre 
                presente Promos al Paso. Debajo de las listas desplegables de selección de ciudad se encuentra la lista de categorías que te 
                permite filtrar las promociones que coincidan con tu selección.</p>
                <p class="plain-text">Una vez que seleccionas la ciudad y pulsas en el botón buscar, se te mostrará una lista con las promociones
                encontradas. En esta lista puedes ver los datos de portada del aviso y para ver los detalles solo debes pulsar en la imagen de la 
                promoción que quieras ver.</p>
            </div>
            <div class="div-img-container">
                <div class="help-menu help-menu-buscar-promos"></div><br/>
                <img id="img-buscar-promos" class="img-help" src="/images/backend/help/s-buscar-promos.png" data-zoom-image="/images/backend/help/buscar-promos.png" />
                <br/><br/>
                <img id="img-buscar-promos-detalle" class="img-help" src="/images/backend/help/s-buscar-promos-detalle.png" data-zoom-image="/images/backend/help/buscar-promos-detalle.png"/>
            </div>
        </div>
    </div>
    <h3>Pasos para publicar</h3>
    <div>
        <div style="width: 100%;">
            <p class="plain-text">Para empezar a publicar tus promociones en Promos al Paso solo tienes que completar 5 simples pasos. 
            La descripción de cada uno de éstos la puedes encontrar en las siguientes solapas. </p>
        </div>
        <?php echo $this->partial("auth/_registrationsteps.phtml"); ?>
        <div style="width: 100%;">
            <p class="plain-text">A continuación se detallan cada uno de estos pasos. A medida que vayas completandolos distintas
            opciones de menú se irán habilitando en el Menú de Comercio.</p>
        </div>
        <div style="width: 100%; text-align: center;">
            <img style="margin: auto; border: #DDDDDD solid 2px;" src="/images/backend/help/menues-backend.png"/><br/><br/>    
        </div>
        <div id="tabs-reg" style="height: 250px;">
            <ul>
                <li><a href="#tabs-reg-1">Registrar Usuario</a></li>
                <li><a href="#tabs-reg-2">Validación de Email</a></li>
                <li><a href="#tabs-reg-3">Cargar datos de comercio</a></li>
                <li><a href="#tabs-reg-4">Administrar Categorías</a></li>
                <li><a href="#tabs-reg-5">Administrar promociones</a></li>
            </ul>
            <div id="tabs-reg-1" style="width: 80%; margin: auto; display: block;">
                <div style="width: 75%; float: left;">
                    <p class="plain-text">La registración es el primer paso que debe realizar el comercio anunciante.
                En este paso se deben ingresar nombre del usuario/comercio, email que servirá para ingresar al sistema de administración, 
                cuit para realizar la facturación y la contraseña del usuario.</p>
                </div>
                <div class="div-img-container">
                    <img id="img-registracion" class="img-help" src="/images/backend/help/s-registration.jpg" data-zoom-image="/images/backend/help/registration.jpg" title="Registración del Usuario"/>
                </div>
            </div>
            <div id="tabs-reg-2" style="width: 80%; margin: auto;">
                <div style="width: 100%;">
                    <p class="plain-text">Una vez terminado el paso de registración el sistema te enviará un email para que 
                    confirmes la creación del usuario. En este email vas a encontrar un link que permitirá validar el email
                    del usuario en el sistema de administración.</p>
                </div>
            </div>
            <div id="tabs-reg-3" style="width: 80%; margin: auto;">
                <div style="width: 75%; float: left;">
                    <p class="plain-text">Se accede al formulario pulsando en el Menú de Comercio en la opción Mis Datos. 
                    Este paso consta de cargar los datos del comercio. Entre ellos están el nombre, 
                    teléfono, email, sitio web y dirección. Es muy importante que cargues tu dirección correctamente, dado que
                    con ella es que la aplicación mobile de Promos al Paso localiza tus promociones.</p>
                    <p class="plain-text">Una vez que hayas cargado la calle, número y la localidad de tu comercio tienes que 
                    ubicar la misma en el mapa pulsando sobre el botón "Localizarme" y validando la misma pulsando en el botón
                    "Confirmar Localización" en la ventana emergente. 
                    </p>
                    <p class="plain-text">Otro elemento importante que debes cargar en este paso es la imagen o logo de tu 
                    comercio. La imagen debe ser preferentemente cuadrada de a lo sumo 1.2 MB de tamaño. Para seleccionar la imagen
                    debes pulsar en el botón "Cargar Imagen" y seleccionar el archivo correspondiente.</p>
                </div>
                <div class="div-img-container">
                    <div class="help-menu help-menu-datos"></div><br/>
                    <img id="img-branch" class="img-help" src="/images/backend/help/s-branch.jpg" data-zoom-image="/images/backend/help/branch.jpg" title="Datos del Comercio"/>
                </div>
            </div>
            <div id="tabs-reg-4" style="width: 80%; margin: auto;">
                <div style="width: 75%; float: left;">
                    <p class="plain-text">Se accede al formulario pulsando en el Menú de Comercio en la opción Mis Categorías.
                    Todos los comercios deben tener asignada al menos una categoría. A partir de ella
                    los clientes pueden realizar búsquedas puntuales por rubro y de esa forma tu anuncio será mostrado. Si
                    no existe una categoría que encaje para tu negocio envíanos un email a soporte@promosalpaso.com y nosotros
                    te ayudaremos a seleccionar la mejor o crear una nueva.</p>
                </div>
                <div class="div-img-container">
                    <div class="help-menu help-menu-categorias"></div><br/>
                </div>
            </div>
            <div id="tabs-reg-5" style="width: 80%; margin: auto;">
                <div style="width: 75%; float: left;">
                    <p class="plain-text">Una vez completados los 4 pasos anteriores del proceso de registración ya estas en 
                    condiciones de publicar tus promociones en Promos al Paso!</p>
                    <p class="plain-text">Para administrar tus promociones debes seleccionar la opción "Mis Promos" en el menú
                    principal. Allí se te mostrará información de las promociones que actualmente se encuentran publicadas en 
                    el apartado "Publicaciones Activas" y un resumen de las promociones anteriores en el apartado "Publicaciones
                    Históricas".</p>
                    <p class="plain-text">A continuación se puede ver una grilla con todas las promociones </p>
                </div>
                <div class="div-img-container">
                    <div class="help-menu help-menu-promos"></div><br/>
                    <img id="img-index-promos" class="img-help" src="/images/backend/help/s-index-promos.png" data-zoom-image="/images/backend/help/index-promos.png" title="Administración de Promociones"/>
                </div>
            </div>
        </div>
    </div>
    <h3>Proceso de publicación</h3>
    <div>
        <div id="tabs-promos" style="height: 500px;">
            <ul>
                <li><a href="#tabs-promo-1">Panel de Promociones</a></li>
                <li><a href="#tabs-promo-2">Portada de Promoción</a></li>
                <li><a href="#tabs-promo-3">Cuerpo de Promoción</a></li>
            </ul>
            <div id="tabs-promo-1" style="width: 80%; margin: auto; display: block;">
                <div style="width: 75%; float: left;">
                    <p class="plain-text">El panel de promociones sirve para tener un vistazo de las promociones que has publicado en el transcurso
                    del tiempo. En el mismo se puede ver un resumen de las promociones actuales, un histórico y la grilla que contiene todas las
                    promos que has publicado.</p>
                    <p class="plain-text">Las Publicaciones Acuales muestran información acerca de las promociones que actualmente están activas.
                    Se consideran promociones activas a aquellas que se encuentren es estado Activo y que el día de la fecha esté comprendido entre
                    la fecha de inicio y fin de la promoción.</p>
                    <p class="plain-text">El Histórico de Publicaciones muestra un resumen cuantitativo de las promociones que se han publicado desde
                    que te has registrado. Se puede ver la cantidad de promos publicadas, la cantidad de promos agrupadas por su valor y las visitas 
                    recibidas por cada valor de promo.</p>
                    <p class="plain-text">Para crear una nueva promo solo tiene que pulsar en el botón nueva promo que se encuentra a la derecha y 
                    el sistema te llevará al formulario de creación de promoción.</p>
                </div>
                <div class="div-img-container">
                    <img id="img-portal-resumen-promos" class="img-help" src="/images/backend/help/s-portal-resumen-promos.png" data-zoom-image="/images/backend/help/portal-resumen-promos.png" title="Resumen de Promos"/>
                    <br/><br/>
                    <img id="img-portal-grilla-promos" class="img-help" src="/images/backend/help/s-portal-grilla-promos.png" data-zoom-image="/images/backend/help/portal-grilla-promos.png" title="Grilla de Promociones"/>
                </div>    
            </div>
            <div id="tabs-promo-2" style="width: 80%; margin: auto; display: block;">
                <div style="width: 75%; float: left;">
                    <p class="plain-text">Llamamos portada de la promoción a la información que se muestra en la lista de promociones
                    resultado de la búsqueda por ubicación geográfica o por ciudad. En esta portada se muestra el nombre del comercio, 
                    un título de promoción, un texto descriptivo, su imagen, su precio o porcentaje y la distancia que separa al usuario 
                    del comercio que ofrece la promo.</p>
                    <p class="plain-text">El título es un texto corto, de 25 caractéres a lo sumo, que tiene por objeto llamar la atención.
                    Éste debe ser corto y efectivo, anunciando descuentos, ofertas, liquidaciones, etc</p>
                    <p class="plain-text">El texto descriptivo es un texto de 60 caracteres que es un resumen de la promoción. Tiene por objetivo
                    hacer que el usuario se interese por el contenido de la promo y visite a la misma.</p>
                    <p class="plain-text">En la portada también se especifica el valor de la misma y si este es un precio o un porcentaje. 
                    El check box "desde" permite agregar dicha palabra acompañando al valor. Esto posibilita promociones rango de precios o 
                    porcentajes de descuento.</p>
                    <p class="plain-text">Por último se ingresa la imagen de la Promo, la cual debe ser representativa y preferentemente de
                    proporciones cuadradas.</p>
                </div>
                <div class="div-img-container">
                    <img style="margin: auto;" width="100%" src="/images/backend/help/portada-promo-item.png"/><br/><br/>
                    <img id="img-portada-promo" class="img-help" src="/images/backend/help/s-portada-promo.png" data-zoom-image="/images/backend/help/portada-promo.png" title="Portada de Promo"/>
                </div>
            </div>
            <div id="tabs-promo-3" style="width: 80%; margin: auto; display: block;">
                <div style="width: 75%; float: left;">
                    <p class="plain-text">El cuerpo principal de la promoción que se muestra en el dispositivo movil se carga en la sección
                    Detalle de Promoción.</p>
                    <p class="plain-text">Código es un valor autogenerado que sirve para identificar la promoción. Tipo de promo indica si la 
                    promoción es un servicio o un producto. Los campos Desde y Hasta especifica el rango de días en los que se publicará la promoción.
                    El campo Unidades sirve para indicar cuantas unidades disponibles quedan del producto o servicio ofrecido. Descripción Larga es
                    el campo que contiene la especificación detallada de la promoción. El estado indica si la promoción es está publicada o no más allá
                    del valor tomado por los campos Desde y Hasta. Visitas indica cuantas veces esa promoción fue seleccionada para su visualización.</p>
                    <p class="plain-text">El costo es el monto en pesos que deseas pagar por día por la publicación de la promoción. Este valor influye en 
                    el ordenamiento de la lista de promos junto con la distancia me media entre el usuario del dispositivo movil y el comercio.</p>
                    <p class="plain-text">Tipo de Alarma especifica si queremos mostrar un aviso informando de cuantas unidades disponibles hay ó de cuantos
                    días restan para la finalización de la promoción ó ninguno de los dos.</p>
                    <p class="plain-text">El botón Previsualizar nos permite ver como se mostraría la promo en el dispositivo movil. Clonar nos permite hacer una
                    copia de la presente promoción para facilitar su replicación. Y guardar persiste los datos de la promoción en el sistema.</p>
                    <p class="plain-text">Costo total de la promo nos indica cuanto es el costo que debemos pagar por la publicación de la promoción en función de
                    los días de vigencia de la misma.</p>
                </div>
                <div class="div-img-container">
                    <img id="img-detalle-promo" class="img-help" src="/images/backend/help/s-detalle-promo.png" data-zoom-image="/images/backend/help/detalle-promo.png" title="Detalle de Promo"/>
                    <br/><br/>
                    <img id="img-promo-mobile" class="img-help" src="/images/backend/help/s-promo-mobile.png" data-zoom-image="/images/backend/help/promo-mobile.png" title="Promo en mobile"/>
                </div>
            </div>
        </div>
    </div>

    <!-- los siguientes puntos se muestran si el usuario está registrado.-->
    <h3>Costos del Servicio y Posicionamiento</h3>
    <div>
        <div style="width: 100%;">
            <p class="plain-text">En esta sección encontrarás toda la información acerca del costo del servicio, como pagar el mismo y en que afecta la elección del precio que eliges para tus promos. En las siguientes solapas encontraras la explicación de cada uno de estos puntos. Si tiene alguna duda con respecto al costo del servicio no dudes en comunicarte a soporte@promosalpaso.com</p>
        </div><br/><br/>
        <div id="tabs-costos" style="height: 680px;">
            <ul>
                <li><a href="#tabs-costos-3">Posicionamiento</a></li>
                <li><a href="#tabs-costos-1">Costo de promoción</a></li>
                <li><a href="#tabs-costos-2">Mis Costos</a></li>
                <li><a href="#tabs-costos-4">Métodos de Pago</a></li>
            </ul>
            <div id="tabs-costos-1" style="width: 90%; margin: auto; display: table;">
                <div style="width: 100%; display: table-row;">
                    <div style="width: 75%; float: left; display: table-cell;">
                        <p class="plain-text">En Promos al Paso tu decides cuanto quieres pagar por el anuncio. El costo diario de cada una de las promociones lo determinas asignando el Costo al dar de alta una promoción. Este valor multiplicado por la cantidad de días (Lunes a Viernes) en el que se va a publicar la promo determina el costo total de la misma.<br/>
                        El costo que pagues por día por la promo influye directamente en el posicionamiento de la misma en la lista de promos que se le muestra a los usuarios de la aplicación movil de Promos al Paso.
                        </p>
                    </div>
                    <div class="div-img-container">
                        <img id="img-promo-costo" class="img-help" src="/images/backend/help/s-promo-costo.png" data-zoom-image="/images/backend/help/promo-costo.png" title="Costo de la Promo"/>
                    </div>
                </div><br/>
                <div style="width: 100%; display: table-row;">
                    <div style="width: 75%; float: left; display: table-cell;">
                        <p class="plain-text">El costo total de la Promo lo puedes ver en la página de creación o edición de Promociones. El mismo se calcula a partir de los días Lunes a Viernes comprendidos entre los campos "Desde" y "Hasta", multiplicado por el Costo seleccionado para la promo.<br/>
                        Por lo tanto, si publicas una promo que vaya de un lunes al siguiente domingo el anuncio aparecerá 7 días pero pagarás 5!!.<br/>
                        Si la promo que estás creando solo está comprendida por el día sábado o domingo, el sistema solo te permitirá seleccionar el menor costo posible.</p>
                    </div>
                    <div class="div-img-container">
                        <img id="img-promo-costo-total" class="img-help" src="/images/backend/help/s-promo-costo-total.png" data-zoom-image="/images/backend/help/promo-costo-total.png" title="Costo Total de la Promo"/>
                    </div>
                </div>
            </div>
            <div id="tabs-costos-2" style="width: 90%; margin: auto; display: table;">
                <div style="display: table-row;">
                    <div style="width: 75%; float: left; display: table-cell;">
                        <p class="plain-text">En la sección <strong>Mis Costos</strong> encontrarás una serie de reportes que te permitirán hacer el seguimiento de los costos de tus publicaciones. Estos reportes son los siguientes:<br/><br/>
                        <strong>Cargos Pendientes: </strong> En este reporte podrás ver los cargos pendientes de pago que tienes imputados. Los cargos se calculan al finalizar cada uno de los <i>Períodos</i> y son el resulado de la sumatoria de la muliplicación del <i>Costo</i> por la cantidad de días anunciados de tus <i>Promos</i> durante el <i>Período</i> indicado.<br/><br/>
                        <strong>Período Actual: </strong> En este reporte podrás ver los gastos incurridos desde el inicio del presente <i>Período</i> hasta el día de la fecha en la que consultas el reporte. Esto te sirve para llevar un control preciso de tus gastos en todo momento.<br/><br/>
                        <strong>Últimos 6 Períodos: </strong> Este reporte te muestra los gastos incurridos en los últimos 6 períodos (3 meses). Este te permite ver como evolucionaron tus gastos en el mediano tiempo.
                        </p>
                    </div>
                    <div class="div-img-container">
                        <img id="img-promos-cargos" class="img-help" src="/images/backend/help/s-promos-cargos.png" data-zoom-image="/images/backend/help/promos-cargos.png" title="Cargos de la Promo"/>
                    </div>
                </div>
                <div style="display: table-row;">
                    <div style="width: 75%; float: left; display: table-cell;">
                        <p class="plain-text">De cada <i>Período</i> se muestra su código, sus fechas límites y el total de costos incurridos en el mismo. Mientras que dentro de cada uno de ellos se puede ver un detalle de dichos costos.<br/>
                        En este datalle se puede ver la cantidad de promos publicadas agrupadas por el <i>Costo</i> de cada una, la cantidad de días anunciados y el subtotal de costos generados por este tipo de promociones.</p>    
                    </div>
                    <div class="div-img-container">
                        <img id="img-promo-costos-detalle" class="img-help" src="/images/backend/help/s-promo-costos-detalle.png" data-zoom-image="/images/backend/help/promo-costos-detalle.png" title="Detalle de cargos"/>
                    </div>
                </div>
            </div>
            <div id="tabs-costos-3" style="width: 90%; margin: auto; display: table;">
                <div style="display: table-row;">
                    <div style="width: 75%; float: left;">
                        <p class="plain-text">Una de los temas más importantes en cualquier medio publicitario es el posicionamiento. Y Promos al Paso no es la excepción. Este posicionamiento se refleja en el orden de la lista de promociones que se muestran en los distintos dispositivos móviles que consultan las promociones. Se sabe que los primeros items de una lista son los más vistos. Es por eso que más allá de la distancia en la que te encuentres, puedes influir en el ordenamiento de esta lista cambiando el <strong>Costo de la Promo</strong> ofrecido.<br/><br/>
                        Promos al Paso ha creado un sistema de ordenamiento que surge de la relación entre el <strong>Costo de la Promo</strong> y la distancia que existe entre el dispositivo que consulta y el comercio que publica el anuncio. De esta forma se creo un sistema equilibrado en la que la distancia y el <strong>Costo de la Promo</strong> influyen en partes iguales en el ordenamiento de las promos.<br/><br/>
                        En la imagen puedes ver que hay anuncios de CotiStore a 715mts que están por encima de la promo de Leather San Justo que está a 308 mts. Esto se debe a que el anunciante CotiStore asignó un <strong>Costo de Promo</strong> mayor que el de Leather San Justo.</p>
                    </div>
                    <div class="div-img-container">
                        <img id="img-mobile-promolist" class="img-help" src="/images/backend/help/s-mobile-promolist.png" data-zoom-image="/images/backend/help/mobile-promolist.png" title="Lista de Promos en dispositivo"/>
                    </div>
                </div>
                <div style="display: table-row;">
                    <div style="width: 75%; float: left;">
                        <p class="plain-text">En la tabla que está a la derecha puedes ver como funciona el <strong>Indice de Ordenamiento</strong>. En las columnas se pueden ver los valores que pueden tomar el <strong>Costo</strong> para las promociones. En este caso se corresponden con $1, $2, $3 y $4. Y en las filas se pueden ver distintas distancias. En el ejemplo hemos tomado 50, 10, 200, 400, 800 y 1000 mts.<br/>
                        Destacado en naranja se puede ver como pagado un costo de $3 a 800mts se puede posicionar antes que una promo que pagó un costo de $1 y se encuentra a menor distancia (200mts).<br>
                        Por otro lado con el ejemplo verde podemos ver que a distancias cortas, una promo que pagó de costo $1 va a estar posicionada antes que una que pago $4 pero se encuentra a 4 veces la distancia (200mts).<br/>
                        Esto permite que los negocios que se encuentren lejos de una via de transito concurrida, pueda competir en posicionamiento con comercios que se encuentren cerca de la misma vía.</p>
                    </div>
                    <div class="div-img-container">
                        <img id="img-promos-ordenamiento" class="img-help" src="/images/backend/help/s-promos-ordenamiento.png" data-zoom-image="/images/backend/help/promos-ordenamiento.png" title="Tabla de ordenamiento"/>
                    </div>
                </div>
                
            </div>
            <div id="tabs-costos-4" style="width: 90%; margin: auto; display: table;">
                <div style="display: table-row;">
                    <div style="width: 75%; float: left;">
                        <p class="plain-text">Dependiendo de la ciudad en la que te encuentre tendrás la posibilidad de pagar tus gastos mediante distintos métodos de pago. A lo sumo dispondrás de hasta 3 métodos de pago que describiremos a continuación.</p>
                    </div>
                    <div class="div-img-container">
                        <img id="img-promo-metodos-pago" class="img-help" src="/images/backend/help/s-promo-metodos-pago.png" data-zoom-image="/images/backend/help/promo-metodos-pago.png" title="Métodos de Pago"/>
                    </div>
                </div>
                <div style="display: table-row;">
                    <div style="width: 75%; float: left;">
                        <p class="plain-text"><strong>Efectivo</strong></p>
                        <p class="plain-text">Solo algunas ciudades tendrán la opción de pago en efectivo. Este método de pago consiste en avisar a Promos al Paso que tienes intenciones se pagar los períodos seleccionados en efectivo. Cuando pulsas en el botón "Efectivo", el sistema te muestra un mensaje indicando que personal del staff de Promos al Paso pasarán por la dirección cargada en el comercio en una fecha a coordinar via email para concretar el pago.</p>
                        <p class="plain-text">Si tu estado de cuenta es deudor, indicando tu intención de pagar en efectivo te permite seguir operando normalmente el sistema por 15 días.</p>
                    </div>
                    <div class="div-img-container">
                         <br/><br/>
                        <img id="img-pago-efectivo" class="img-help" src="/images/backend/help/s-pago-efectivo.png" data-zoom-image="/images/backend/help/pago-efectivo.png" title="Pago en efectivo"/>
                    </div>
                </div>
                <div style="display: table-row;">
                    <div style="width: 75%; float: left;">
                        <p class="plain-text"><strong>Depósito/Transferencia Bancaria</strong></p>
                        <p class="plain-text">Este método de pago consiste en dos pasos. Por un lado obtener la información para efectuar la transferencia y luego de realizada la misma, informarla en Promos al Paso.</p>
                        <p class="plain-text">Para obtener la información tienes que seleccionar los períodos a pagar. Luego pulsa el botón "Depósito/Transferencia Bancaria" y en el popup que se despliega pulsa en el botón "Imprimir Info". Al hacer esto se abrirá una nueva ventana que contiene todos los datos para realizar el depósito o transferencia.</p>
                        <p class="plain-text">Luego de efectuado el depósito o transferencia repite nuevamente los pasos anteriores, selecciona los períodos pagados, pulsa el botón "Depósito/Transferencia Bancaria" y en la ventana emergente carga los datos de la operación realizada. Debes ingresar tipo de operación, banco, fecha y número de control de corresponder. Una vez cargados estos datos pulsa en el botón "Informar Pago" para terminar el procedimiento.</p>
                        <p class="plain-text">Al realizar esta operación, el pago queda pendiente de validación y puedes utilizar el sistema normalmente mientras tanto. Cualquier duda o inconveniente no dudes en enviar un email a administracion@promosalpaso.com.</p>
                    </div>
                    <div class="div-img-container">
                        <img id="img-metodo-pago-transferencia" class="img-help" src="/images/backend/help/s-metodo-pago-transferencia.png" data-zoom-image="/images/backend/help/metodo-pago-transferencia.png" title="Transferencia/Depósito"/>
                    </div>
                </div>
                <div style="display: table-row;">
                    <div style="width: 75%; float: left;">
                        <p class="plain-text"><strong>Mercado Pago</strong></p>
                        <p class="plain-text">Para pagar por MP debes tener una cuenta en esta pasarela de pagos. Una vez que hayas seleccionado los períodos que deseas pagar y pulsa en el botón "Mercado Pago". Esto te llevará a una ventana emergente de MP que te permitirá pagar como desees. Una vez terminada la operación la ventana emergente se cierra e informa automaticamente al sistema de tu pago.</p>
                    </div>
                    <div class="div-img-container">
                        <img id="img-metodo-pago-transferencia" class="img-help" src="/images/backend/help/MercadoPago.png" title="Mercado Pago"/>
                    </div>
                </div>
            </div>
        </div>                      
    </div>
</div>


