 <script>
    $(function() {
        $( "#accordion" ).accordion({
            collapsible: true
        });
    });
</script>

<h3>¿Qué es Promos al Paso?</h3>
<p class="plain-text">bla bla bla bla</p>

<div id="accordion">
    <h3>Registración</h3>
    <div>
        <?php echo $this->partial("auth/_registrationsteps.phtml"); ?>
        <ul>
            <li>
                <p class="plain-text plain-title">Registración</p>
                <div style="width: 80%; margin: auto;">
                    <div style="width: 75%;">
                        <p class="plain-text">La registración es el primer paso que debe realizar el comercio anunciante.
                    En este paso se deben ingresar nombre del usuario/comercio, email que servirá para ingresar al sistema de administración, 
                    cuit para realizar la facturación y la contraseña del usuario.</p>
                    </div>
                    <img style="margin: auto;" src="/images/backend/help/s-registration.jpg"/>
                </div>
            </li>
            <li>
                <p class="plain-text plain-title">Validación de Email</p>
                <div style="width: 80%; margin: auto;">
                    <div style="width: 75%;">
                        <p class="plain-text">Una vez terminado el paso de registración el sistema te enviará un email para que 
                        confirmes la creación del usuario. En este email vas a encontrar un link que permitirá validar el email
                        del usuario en el sistema de administración.</p>
                    </div>
                </div>
            </li>
            <li>
                <p class="plain-text plain-title">Cargar datos de comercio</p>
                <div style="width: 80%; margin: auto;">
                    <div style="width: 75%;">
                        <p class="plain-text">Este paso consta de cargar los datos del comercio. Entre ellos están el nombre, 
                        teléfono, email, sitio web y dirección. Es muy importante que cargues tu dirección correctamente, dado que
                        con ella es que la aplicación mobile de Promos al Paso localiza tus promociones.</p>
                        <p class="plain-text">Una vez que hayas cargado la calle, número y la localidad de tu comercio tienes que 
                        ubicar la misma en el mapa pulsando sobre el botón "Localizarme" y validando la misma pulsando en el botón
                        "Confirmar Localización" en la ventana emergente. 
                        </p>
                        <p class="plain-text">Otro elemento importante que debes cargar en este paso es la imagen o logo de tu 
                        comercio. La imagen debe ser preferentemente cuadrada de a lo sumo 1.2 MB de tamaño. Para seleccionar la imagen
                        debes pulsar en el botón "Cargar Imagen" y seleccionar el archivo correspondiente.</p>
                    </div>
                    <img style="margin: auto;" src="/images/backend/help/s-branch.jpg"/>
                </div>
            </li>
            <li>
                <p class="plain-text plain-title">Cargar categorías del comercio</p>
                <div style="width: 80%; margin: auto;">
                    <div style="width: 75%;">
                        <p class="plain-text">Todos los comercios deben tener asignada al menos una categoría. A partir de ella
                        los clientes pueden realizar búsquedas puntuales por rubro y de esa forma tu anuncio será mostrado. Si
                        no existe una categoría que encaje para tu negocio envíanos un email a soporte@promosalpaso.com y nosotros
                        te ayudaremos a seleccionar la mejor o crear una nueva.</p>
                    </div>
                    <img style="margin: auto;" src="/images/backend/help/s-categories.jpg"/>
                </div>
            </li>
            <li>
                <p class="plain-text plain-title">Crear promociones</p>
                <div style="width: 80%; margin: auto;">
                    <div style="width: 75%;">
                        <p class="plain-text">Una vez completados los 4 pasos anteriores del proceso de registración ya estas en 
                        condiciones de publicar tus promociones en Promos al Paso!</p>
                        <p class="plain-text">Para administrar tus promociones debes seleccionar la opción "Mis Promos" en el menú
                        principal. Allí se te mostrará información de las promociones que actualmente se encuentran publicadas en 
                        el apartado "Publicaciones Activas" y un resumen de las promociones anteriores en el apartado "Publicaciones
                        Históricas".</p>
                        <p class="plain-text">A continuación se puede ver una grilla con todas las promociones </p>
                    </div>
                    <img style="margin: auto;" src="/images/backend/help/s-index-promos.png"/>
                </div>
            </li>
        </ul>
    </div>
    <h3>Proceso de publicación</h3>
    <div>bla bla bla bla</div>

    <!-- los siguientes puntos se muestran si el usuario está registrado.-->
    <h3>Proceso de contabilización</h3>
    <div>bla bla bla bla</div>

    <h3>Proceso de pago</h3>
    <div>bla bla bla bla</div>
</div>


