<script type="text/javascript" src="./scripts/jquery.jcarousel.min.js"></script>
<!--
<div class="row">
    <div class="span6 offset3" id="titulo" align="center">
            <h1>¿Qué es promos al paso?</h1>
    </div>
</div>
<hr class="hr-subtitle"/>-->
<?php echo $this->partial("index/_alert.phtml"); ?>
<div class="row-fluid">
    <div class="span4 well" style="background-color: #333333;">
        <div style="float: left; width: 25%;"><a href="https://www.facebook.com/PromosAlPaso" target="_blank"><img src="/images/backend/me_gusta.png" width="70px" alt=""></a></div>
        <div style="float: right; width: 75%;">Para mantenerte informado, dale "Me Gusta" a Promos al Paso. Ahí te iremos informando de nuestros pasos.</div>
    </div>
    <div class="span4 well" style="background-color: #333333;">
        <div style="float: left; width: 20%;"><img src="/images/backend/mobile.pap.png" width="45px" alt=""></div>
        <div style="float: right; width: 80%;">Si sos un comercio ya te podes registrar!! El sábado 25 hacemos el lanzamiento de Promos al Paso para los usuarios finales.</div>
    </div>
    <div class="span4 well" style="background-color: #333333;">
        <div style="float: left; width: 25%;"><a href="http://www.youtube.com/channel/UCKV6rVTtx2ny_mRWoEp6D4A" target="_blank"><img src="/images/backend/youtube.png" width="70px" alt=""></a></div>
        <div style="float: right; width: 75%;">En nuestro canal de YouTube podes ver videos de como registrarte y crear promos. Mirá los videos y verás que es muy facil!</div>
    </div>
</div>
<div class="row-fluid">
    <div class="span4 well">
        <a href="<?php echo $this->url(array('controller'=>'auth','action'=>'login'));?>" class="home-link">
            <div style="display: inline; float: left;">
                <img src="/images/backend/goto-login.png" alt="Buscar Promociones">
            </div>
            <div display: inline; float: right;>
                <span class="home-title-section">Anunciar</span>
                <span class="home-text">¿Sos un comercio y tenes promociones y ofertas para ofrecer?. Regístrate e ingresa
                al sistema publicador de Promos al Paso. Es muy facil y rápido!!</span>
            </div>
        </a>
    </div>
    <div class="span4 well">
        <a href="<?php echo $this->url(array('controller'=>'promotion','action'=>'search'));?>" class="home-link">
            <div style="display: inline; float: left;">
                <img src="/images/backend/goto-search.png" alt="Buscar Promociones"/>
            </div>
            <div display: inline; float: right;>
                <span class="home-title-section">Buscar</span>
                <span class="home-text">
                    Busca promociones por ciudad. Encuentra las mejores ofertas en todos los rubros
            en todas las ciudades en las que esté Promos al Paso presente.
                </span>
            </div>
        </a>
    </div>
    <div class="span4 well">
        <a href="<?php echo $this->url(array('controller'=>'index','action'=>'help'));?>" class="home-link">
            <div style="display: inline; float: left;">
                <img src="/images/backend/goto-help.png" alt="Buscar Promociones">
            </div>
            <div display: inline; float: right;>
                <span class="home-title-section">Ayuda</span>
                <span class="home-text">¿Qué es Promos al Paso?. ¿Como encuentro promociones?. ¿Cómo hago para publicar?. ¿En donde se verán mis promociones?.</span>
            </div>
        </a>
    </div>
</div>
<div class="row-fluid">
    <div class="span10 offset1 well pagination-centered">
        <p>Promos al Paso te permitirá ahorrar dinero y tiempo mostrandote en tu celular las mejores promociones cerca de donde te encuentres.</p>
        <h5>Disponible para</h5>
        <div style="display: inline">
            <a href="#"><img title="Android" class="platform-icon" src="/images/backend/android-icon.png"/></a>
            <a href="#"><img title="Windows Phone" class="platform-icon" src="/images/backend/wp-icon.png"/></a>
            <a href="#"><img title="BlackBerry" class="platform-icon" src="/images/backend/blackberry-icon.png"/></a>
            <a href="#"><img title="Symbian" class="platform-icon" src="/images/backend/symbian-icon.png"/></a>
            <a href="#"><img title="iPhone" class="platform-icon" src="/images/backend/apple-icon.png"/></a>
            <a href="#"><img title="Cualquier browser HTML5" class="platform-icon" src="/images/backend/html5-icon.png"/></a>
        </div>
    </div>
</div>
<a id="a_carousel"/>
<div class="row-fluid pagination-centered">
    <div class="span10 offset1">
    <div id="mycarousel" class="jcarousel-skin-ie7" style="padding-left: 40px;">
        <ul><!-- The content will be dynamically loaded in here --></ul>
    </div>
    </div>
    <div class="span1">&nbsp;</div>
</div>
<input type="hidden" id="slider_promos"/>
<script type="text/javascript" src="/scripts/prototype.js"></script>
<script type="text/javascript">
    function mycarousel_itemLoadCallback(carousel, state)
    {
        // Check if the requested items already exist
        if (carousel.has(carousel.first, carousel.last)) {
            return;
        }
        var myAjax = new Ajax.Request(
        _baseAjaxUri + 'getfeatured',
            {
                method:'get',
                parameters: {first: carousel.first,
                             last: carousel.last},
                onSuccess: carouselSuccess,
                onError: carouselError
        });
    };
    
    function carouselSuccess(data){
        var carousel = jQuery('#mycarousel').data('jcarousel');
        var response = data.responseText;
        
        if(data.responseText.indexOf("<br />") >= 0)
            response = data.responseText.substring(0, data.responseText.indexOf("<br />"));
        if(response.indexOf("<div")>=0)
            response = response.substring(0, response.indexOf("<div")); 
        
        var jsondata = JSON.parse(response);
        jQuery("#slider_promos").val(response);
        mycarousel_itemAddCallback(carousel, carousel.first, carousel.last, jsondata);    
    }
    
    function carouselError(data){
       alert(data);    
    }

    function mycarousel_itemAddCallback(carousel, first, last, data)
    {
        if(data.total < 6){
            jQuery('#mycarousel').hide();  
            return;
        }
        // Set the size of the carousel
        //carousel.size(parseInt(jQuery('total', xml).text()));
        carousel.size(parseInt(data.total));

        jQuery.each(data.promos, function(i,item){
            carousel.add(first + i, mycarousel_getItemHTML(item));
        });
        jQuery('#mycarousel').show();
        /*        
        jQuery('image', xml).each(function(i) {
            carousel.add(first + i, mycarousel_getItemHTML(jQuery(this).text()));
        });*/
    };

    /**
     * Item html creation helper.
     */
    function mycarousel_getItemHTML(promo)
    {
        var promo_html = '<a onClick="FillPromotionById('+promo.promotion_id+');"><div class="slider_promo">';
            promo_html += '  <div class="slider_localidad">'+promo.city+'</div>';
            promo_html += '  <div><img src="'+promo.path+'" style="height:60px;" class="img-polaroid"/></div>';
            promo_html += '  <div class="slider_displayed_text">'+promo.name+'</div>';
            promo_html += '  <div class="slider_precio">'+promo.promo_value+'</div>';
            promo_html += '  <div class="slider_displayed_text" style="font-weight: bold; color: #42962F">'+promo.displayed_text+'</div></div></a>';;

        return promo_html;
    };
    
    function mycarousel_initCallback(carousel)
    {
        // Disable autoscrolling if the user clicks the prev or next button.
        carousel.buttonNext.bind('click', function() {
            carousel.startAuto(0);
        });
        carousel.buttonPrev.bind('click', function() {
            carousel.startAuto(0);
        });
    
        // Pause autoscrolling if the user moves with the cursor over the clip.
        carousel.clip.hover(function() {
            carousel.stopAuto();
        }, function() {
            carousel.startAuto();
            });
    }; 
        
    jQuery(document).ready(function() {
        jQuery('#mycarousel').jcarousel({
            // Uncomment the following option if you want items
            // which are outside the visible range to be removed
            // from the DOM.
            // Useful for carousels with MANY items.

            // itemVisibleOutCallback: {onAfterAnimation: function(carousel, item, i, state, evt) { carousel.remove(i); }},
            initCallback: mycarousel_initCallback,
            itemLoadCallback: mycarousel_itemLoadCallback, //{onBeforeAnimation: mycarousel_itemLoadCallback},
            animation: 2000,
            auto: 6,
            scroll: 1,
            size: 6,
            wrap: 'last',
        });
        jQuery('#mycarousel').hide();
    });
    
    function FillPromotionById(promo_id){
        var jsondata = JSON.parse(jQuery("#slider_promos").val());
        jQuery.each(jsondata.promos, function(i,item){
            if(item.promotion_id == promo_id){
                FillPromotion(item);
                return false;
            }
        });
    }
</script>
<?php echo $this->partial("promotion/_promobody.phtml"); ?>