<script type="text/javascript" src="./scripts/jquery.jcarousel.min.js"></script>
<!--
<div class="row">
    <div class="span6 offset3" id="titulo" align="center">
            <h1>¿Qué es promos al paso?</h1>
    </div>
</div>
<hr class="hr-subtitle"/>-->
<?php echo $this->partial("index/_alert.phtml"); ?>
<div class="row-fluid">
    <div class="span10 offset1 well">
        <p>Promos al paso es un sistema que comunica a los comercios con los clientes para hacerle llegar a éstos las promociones vigentes.</p>
        <p>El sistema está compuesto por dos módulos. Uno es una aplicación para teléfonos inteligentes (smartphones) y el otro es una aplicación web que le permite a los comercios administrar los anuncios de las distintas promociones.</p>
        <p>Promos al Paso se caracteriza por ser simple tanto para los clientes finales como para los anunciantes. Con el objetivo de que ingresando pocos datos éstos últimos pueden hacer llegar las promociones a los celulares de los clientes finales.</p>
    </div>
</div>
<div class="row-fluid">
    <div class="span4 offset4" align="center">
        <a class="btn" href="<?php echo 'auth/signup'; ?>">Registrarme como Anunciante</a>
    </div>
</div>
<a id="a_carousel"/>
<div class="row-fluid pagination-centered">
    <div class="span10 offset1">
    <div id="mycarousel" class="jcarousel-skin-ie7" style="padding-left: 40px;">
        <ul><!-- The content will be dynamically loaded in here --></ul>
    </div>
    </div>
    <div class="span1">&nbsp;</div>
</div>
<input type="hidden" id="slider_promos"/>
<script type="text/javascript" src="/scripts/prototype.js"></script>
<script type="text/javascript">
    function mycarousel_itemLoadCallback(carousel, state)
    {
        // Check if the requested items already exist
        if (carousel.has(carousel.first, carousel.last)) {
            return;
        }
        var myAjax = new Ajax.Request(
        _baseAjaxUri + 'getfeatured',
            {
                method:'get',
                parameters: {first: carousel.first,
                             last: carousel.last},
                onSuccess: carouselSuccess,
                onError: carouselError
        });
    };
    
    function carouselSuccess(data){
        var carousel = jQuery('#mycarousel').data('jcarousel');
        var response = data.responseText;
        
        if(data.responseText.indexOf("<br />") >= 0)
            response = data.responseText.substring(0, data.responseText.indexOf("<br />"));
        if(response.indexOf("<div")>=0)
            response = response.substring(0, response.indexOf("<div")); 
        
        var jsondata = JSON.parse(response);
        jQuery("#slider_promos").val(response);
        mycarousel_itemAddCallback(carousel, carousel.first, carousel.last, jsondata);    
    }
    
    function carouselError(data){
       alert(data);    
    }

    function mycarousel_itemAddCallback(carousel, first, last, data)
    {
        if(data.total < 6){
            jQuery('#mycarousel').hide();  
            return;
        }
        // Set the size of the carousel
        //carousel.size(parseInt(jQuery('total', xml).text()));
        carousel.size(parseInt(data.total));

        jQuery.each(data.promos, function(i,item){
            carousel.add(first + i, mycarousel_getItemHTML(item));
        });
        jQuery('#mycarousel').show();
        /*        
        jQuery('image', xml).each(function(i) {
            carousel.add(first + i, mycarousel_getItemHTML(jQuery(this).text()));
        });*/
    };

    /**
     * Item html creation helper.
     */
    function mycarousel_getItemHTML(promo)
    {
        var promo_html = '<a onClick="FillPromotionById('+promo.promotion_id+');"><div class="slider_promo">';
            promo_html += '  <div class="slider_localidad">'+promo.city+'</div>';
            promo_html += '  <div><img src="'+promo.path+'" style="height:60px;" class="img-polaroid"/></div>';
            promo_html += '  <div class="slider_displayed_text">'+promo.name+'</div>';
            promo_html += '  <div class="slider_precio">'+promo.promo_value+'</div>';
            promo_html += '  <div class="slider_displayed_text" style="font-weight: bold; color: #42962F">'+promo.displayed_text+'</div></div></a>';;

        return promo_html;
    };
    
    function mycarousel_initCallback(carousel)
    {
        // Disable autoscrolling if the user clicks the prev or next button.
        carousel.buttonNext.bind('click', function() {
            carousel.startAuto(0);
        });
        carousel.buttonPrev.bind('click', function() {
            carousel.startAuto(0);
        });
    
        // Pause autoscrolling if the user moves with the cursor over the clip.
        carousel.clip.hover(function() {
            carousel.stopAuto();
        }, function() {
            carousel.startAuto();
            });
    }; 
        
    jQuery(document).ready(function() {
        jQuery('#mycarousel').jcarousel({
            // Uncomment the following option if you want items
            // which are outside the visible range to be removed
            // from the DOM.
            // Useful for carousels with MANY items.

            // itemVisibleOutCallback: {onAfterAnimation: function(carousel, item, i, state, evt) { carousel.remove(i); }},
            initCallback: mycarousel_initCallback,
            itemLoadCallback: {onBeforeAnimation: mycarousel_itemLoadCallback},
            animation: 2000,
            auto: 2,
            scroll: 1,
            wrap: 'circular',
        });
        jQuery('#mycarousel').hide();
    });
    
    function FillPromotionById(promo_id){
        var jsondata = JSON.parse(jQuery("#slider_promos").val());
        jQuery.each(jsondata.promos, function(i,item){
            if(item.promotion_id == promo_id){
                FillPromotion(item);
                return false;
            }
        });
    }
</script>
<?php echo $this->partial("promotion/_promobody.phtml"); ?>