<?php
//echo $t->_("This is my first translation")."<br/>";
echo '¿Qué es promos al paso?
Promos al paso es un sistema que comunica a los comercios con los clientes para hacerle llegar a éstos las promociones vigentes.

El sistema está compuesto por dos módulos. Uno es una aplicación para teléfonos inteligentes (smartphones) y el otro es una aplicación web que le permite a los comercios administrar los anuncios de las distintas promociones.

Promos al Paso se caracteriza por ser simple tanto para los clientes finales como para los anunciantes. Con el objetivo de que ingresando pocos datos éstos últimos pueden hacer llegar las promociones a los celulares de los clientes finales.
';
?>
<a href="<?php echo 'auth/signup'; ?>">SIGNUP</a>;