<div class="row-fluid">
    <div class="row">
        <div class="pagination-centered" id="titulo">
            <h1>Noticias</h1>
        </div>
    </div>
    <hr class="hr-subtitle"/>
    <div class="row-fluid">
    <table style="width: 100%; background-color: transparent;">
        <tr>
            <td colspan="2" class="home-title-section" style="width: 100%; margin-top: 20px;">EN CONSTRUCCIÓN</td>
        </tr>
        <tr>
            <td colspan="2" align="center">
                <img style="height: 150px; margin-top: 20px;" src="/images/backend/under-construction.png" alt=""/>
            </td>
        </tr>
    </table>
    </div>
</div>