<div class="row-fluid pagination-centered">
    <table style="margin: auto;">
        <tr>
            <td><img id="img-step-1" class="steplarge" src="/images/backend/step-1-icon.png"/></td>
            <td><img class="arrowsteplarge" src="/images/backend/arrows-right-icon.png"/></td>
            <td><img id="img-step-2" class="steplarge" src="/images/backend/step-2-icon.png"/></td>
            <td><img class="arrowsteplarge" src="/images/backend/arrows-right-icon.png"/></td>
            <td><img id="img-step-3" class="steplarge" src="/images/backend/step-3-icon.png"/></td>
            <td><img class="arrowsteplarge" src="/images/backend/arrows-right-icon.png"/></td>
            <td><img id="img-step-4" class="steplarge" src="/images/backend/step-4-icon.png"/></td>
            <td><img class="arrowsteplarge" src="/images/backend/arrows-right-icon.png"/></td>
            <td><img id="img-step-5" class="steplarge" src="/images/backend/step-5-icon.png"/></td>
        </tr>
        <tr>
            <td><span id="span-step-1" class="steplarge stepname">Registración</span></td>
            <td>&nbsp;</td>
            <td><span id="span-step-2" class="steplarge stepname">Validación Email</span></td>
            <td>&nbsp;</td>
            <td><span id="span-step-3" class="steplarge stepname">Datos de Comercio</span></td>
            <td>&nbsp;</td>
            <td><span id="span-step-4" class="steplarge stepname">Categorías Comercio</span></td>
            <td>&nbsp;</td>
            <td><span id="span-step-5" class="steplarge stepname">Creación Promociones</span></td>
        </tr>
    </table>
</div>
<script type="text/javascript">
    /*Ilumina el paso pasado por parámentro, apagando los demás.*/
    function highlightStep(step){
        for(var i = 1; i <= 5; i++){
            if(step == i){
                $("#img-step-"+i).attr('src', '/images/backend/step-'+i+'-icon-highlight.png');
                //$("#span-step-"+i).removeClass('stepname');
                $("#span-step-"+i).addClass('stepnamehighlighted');
            }
            else{
                $("#img-step-"+i).attr('src', '/images/backend/step-'+i+'-icon.png');    
                $("#span-step-"+i).removeClass('stepnamehighlighted');
                //$("#span-step-"+i).addClass('stepname');
            }
        }
    }    
</script>