<div id="view-content" class="ui-widget-content ui-corner-all">
    <p>
        Felicitaciones <?php echo $this->escape($this->name); ?>! Ya has activado tu cuenta. Ahora podrás cargar toda la información de tu negocio y publicar todas las promociones que quieras.
    </p>
</div>

<a href="<?=$this->url(array('controller'=>'auth','action'=>'login'))?>">Pulsa aquí para ingresar al backend de Promos al Paso</a>