<div class="row-fluid">
    <div class="row">
        <div class="pagination-centered" id="titulo">
                <h1>Bienvenido!!</h1>
        </div>
    </div>
    <hr class="hr-subtitle"/>
    <div class="row">
        <div class="pagination-centered">
            <p>
                Felicitaciones <?php echo $this->escape($this->name); ?>! Ya has activado tu cuenta. 
            </p>
            <p>
                Primero deberás cargar la información sobre tu negocio y luego podrás publicar todas las promociones que quieras.
            </p>
        </div>
    </div>
    <div class="pagination-centered">
        <a class="btn btn-large" href="<?=$this->url(array('controller'=>'auth','action'=>'login'), 'default', true)?>">Ingresar al Gestor de Promos al Paso</a>
    </div>
</div>

