    
    Welcome <?php
               $auth = Zend_Auth::getInstance();
               if($auth->hasIdentity()) {
                    $identity = $auth->getIdentity();
               }else{
                    $role = 'guest';
               } 
            echo $identity->name; ?>,<br>

    This is your home page<br>

    <a href="<?=$this->url(array('controller'=>'auth','action'=>'logout'))?>">click here to logout</a>
