<?php
    if(isset($this->errorMessage)){
        echo $this->errorMessage;
    }
    $this->form->setAction($this->url());
    //echo $this->form;
    $form = $this->form;
?>
<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
<div align="center">
    <table>
        <tr>
            <td colspan="2" align="center" valign="middle" height="100px">
                <div style="background-image: url(/images/backend/tit-login.png); background-repeat:no-repeat; background-position: center; height: 50px;">&nbsp;</div>
            </td>
        </tr>
        <tr>
            <td align="right"><?php echo $form->email->renderLabel(); ?></td>
            <td><?php echo $form->email->renderViewHelper(); ?></td>
        </tr>
        <tr>
            <td align="right"><?php echo $form->password->renderLabel(); ?></td>
            <td><?php echo $form->password->renderViewHelper(); ?></td>
        </tr>
        <tr>
            <td colspan="2" align="center"><?php echo $form->login->renderViewHelper(); ?></td>
        </tr>
    </table>
</div>
</form>
    <span class="info">¿Aún no sos anunciante de Promos al Paso?. Si querés serlo regístrate pulsando el trébol -> 
        <a href="<?=$this->url(array('controller'=>'auth','action'=>'signup'))?>">
            <img src="/images/backend/shamrock.png" width="20px" height="20px"></img>
        </a> 
    </span>
