<?php
    $messages = $this->form->getMessages();
    $this->form->setAction($this->url());
    $form = $this->form;
?>
<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" class="form-horizontal well">
    <div class="row">
        <div class="span6 offset3" id="titulo">
                <h1>Ingresar al Backend</h1>
        </div>
    </div>
    <hr class="hr-subtitle"/>
    <?php echo $this->errorMessage($this->form, $messages); ?>
    <div class="row span6 offset3">
            <div class="control-group">
                <?php echo $form->email->renderLabel(); ?>
                <div class="controls">
                    <?php echo $form->email->renderViewHelper(); ?>
                </div>
            </div>
            <div class="control-group">
                <?php echo $form->password->renderLabel(); ?>
                <div class="controls">
                    <?php echo $form->password->renderViewHelper(); ?>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <?php echo $form->login->renderViewHelper(); ?>
                </div>
            </div>
            <div class="control-group">
                <div class="well">
                    <p>¿Aún no sos anunciante en Promos al Paso?. Si querés serlo regístrate pulsando el 
                        <a href="<?=$this->url(array('controller'=>'auth','action'=>'signup'))?>">
                            <img src="/images/backend/shamrock.png" width="20px" height="20px"></img>
                        </a> 
                    </p>
                </div>
            </div>
</div>
</form>
    
    