<?php
    $messages = $this->form->getMessages();
    $this->form->setAction($this->url());
    $form = $this->form;
?>
<form id="content-form" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" class="form-horizontal">
    <div class="row-fluid">    
        <div class="row">
            <div class="span6 offset3" id="titulo">
                    <h1>Ingresar al Gestor de Promos</h1>
            </div>
        </div>
        <hr class="hr-subtitle"/>
        <?php echo $this->errorMessage($this->form, $messages); ?>
        <?php echo $this->partial("index/_alert.phtml"); ?>
    </div>
    <div class="row span6 offset3">
        <div class="control-group">
            <?php echo $form->email->renderLabel(); ?>
            <div class="controls">
                <?php echo $form->email->renderViewHelper(); ?>
            </div>
        </div>
        <div class="control-group">
            <?php echo $form->password->renderLabel(); ?>
            <div class="controls">
                <?php echo $form->password->renderViewHelper(); ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <?php echo $form->login->renderViewHelper(); ?>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button class="btn-link" onclick="resetPassword();" type="button">Restablecer Contraseña</button>
            </div>
        </div>
        <div class="control-group">
            <div align="center">
                <p>¿Aún no sos anunciante en Promos al Paso?</p>
                <p> Si querés serlo regístrate pulsando  
                    <a href="<?=$this->url(array('controller'=>'auth','action'=>'signup'))?>">
                        <img src="/images/backend/shamrock-aqui.png" style="width: 30px; height: 30px;"></img>
                    </a>
                </p> 
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    $('#content-form').validate({
        rules: {
          email: {
            required: true,
            email: true
          },
          password: {
              minlength: 2,
            required: true
          },
        },
        highlight: function(element) {
            $(element).closest('.control-group').removeClass('success').addClass('error');
            
        },
        success: function(element) {
            $(element).text('OK!').addClass('valid')
            $(element).closest('.control-group').removeClass('error').addClass('success');
            
        }
      });
</script>
    