<?php
    if(isset($this->errorMessage)){
        echo $this->errorMessage;
    }
    //$this->form->setAction($this->url());
    //echo $this->form;
    //$form = $this->form;
?>
<div align="center">
    <table>
        <tr>
            <td colspan="2" align="center" valign="middle" height="100px">
                <div style="background-image: url(/images/backend/tit-activacion.png); background-repeat:no-repeat; background-position: center; height: 50px;">&nbsp;</div>
            </td>
        </tr>
        <tr>
            <td>
                <div id="view-content">
                    <p>Aún no has activado tu cuenta. Si quieres que se te re-envíe el email de activación, pulsa el trebol.</p>
                    <a id="linkresendemail"><img src="/images/backend/shamrock.png"></a>
                </div>
            </td>
        </tr>
    </table>
</div>

