<?php
    $messages = $this->form->getMessages();
    $this->form->setAction($this->url());
    $form = $this->form;
?>
<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
    <div align="center">
        <table>
            <tr>
                <td align="center" valign="middle" height="75px">
                    <div style="background-image: url(/images/backend/tit-activacion.png); background-repeat:no-repeat; background-position: center; height: 50px;">&nbsp;</div>
                    <hr/>
                    <?php echo $this->errorMessage($this->form, $messages); ?>
                </td>
            </tr>
            <tr>
                <td>
                    <div id="view-content" class="ui-widget-content ui-corner-all">
                        <p>Aún no has activado tu cuenta. Si quieres que se te re-envíe el email de activación, pulsa el trebol.</p>
                    </div>
                </td>
            </tr>
            <tr>
                <td align="center">
                    <?php echo $form->submit->renderViewHelper(); ?>
                </td>
            </tr>
        </table>
    </div>
    <?php echo $form->email->renderViewHelper(); ?>
</form>
