<div align="center">
        <table>
            <tr>
                <td align="center" valign="middle" height="75px">
                    <div style="background-image: url(/images/backend/tit-activacion.png); background-repeat:no-repeat; background-position: center; height: 50px;">&nbsp;</div>
                    <hr/>
                </td>
            </tr>
            <tr>
                <td valign="middle">
                    <div id="view-content" class="ui-widget-content ui-corner-all">
                        <p>En breve recibirás un email que te permitirá activar tu cuenta.</p>
                    </div>
                </td>
            </tr>
        </table>
    </div>

