<div class="row-fluid">
    <div class="row">
        <div class="pagination-centered" id="titulo">
                <h1>Proceso de Activación</h1>
        </div>
    </div>
    <hr class="hr-subtitle"/>
    <div class="row pagination-centered">
        <h3>Gracias por registrarte!!!</h3>
        <p>En breve recibirás un email que te permitirá activar tu cuenta.</p>
        <p>Si no lo encuentras en tu bandeja de entrada, fíjate en la carpeta de span..</p>
    </div>
</div>

