<div class="row">
        <div class="span6 offset3" id="titulo">
                <h1>Proceso de Activación</h1>
        </div>
    </div>
    <hr class="hr-subtitle"/>
    <?php echo $this->errorMessage($this->form, $messages); ?>
<div align="center">
        <table>
            <tr>
                <td valign="middle">
                        <h4>Gracias por registrarte!!!</h4>
                        <p>En breve recibirás un email que te permitirá activar tu cuenta.</p>
                </td>
            </tr>
        </table>
    </div>

