<?php
    $messages = $this->form->getMessages();
    $this->form->setAction($this->url());
    $form = $this->form;
?>
<form id="content-form" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" class="form-horizontal">
    <div class="row-fluid">
        <div class="row">
            <div class="pagination-centered">
                <h1>Registrarse</h1>
            </div>
        </div>
        <hr class="hr-subtitle"/>
        <?php echo $this->errorMessage($this->form, $messages); ?>
        <?php echo $this->partial("index/_alert.phtml"); ?>
        <div class="row pagination-centered">
            <p>Luego de registrarte se te enviará un e-mail en el cual encontrarás un link para activa tu cuenta.</p>
            <p>Una vez que hayas activado tu cuenta, podrás cargar los datos de tu comercio y luego tus promociones.</p>
        </div>
        <div class="row span6 offset3">
            <div class="control-group">
                <?php echo $form->email->renderLabel(); ?>
                <div class="controls">
                    <?php echo $form->email->renderViewHelper(); ?>
                </div>
            </div>
            <div class="control-group">
                <?php echo $form->name->renderLabel(); ?>
                <div class="controls">
                    <?php echo $form->name->renderViewHelper(); ?>
                </div>
            </div>
            <div class="control-group">
                <?php echo $form->cuit->renderLabel(); ?>
                <div class="controls">
                    <?php echo $form->cuit->renderViewHelper(); ?>
                </div>
            </div>
            <div class="control-group">
                <?php echo $form->password->renderLabel(); ?>
                <div class="controls">
                    <?php echo $form->password->renderViewHelper(); ?>
                </div>
            </div>
            <div class="control-group">
                <?php echo $form->confirmPassword->renderLabel(); ?>
                <div class="controls">
                    <?php echo $form->confirmPassword->renderViewHelper(); ?>
                </div>
            </div>
        </div>
        <div class="row-fluid span2 offset5">
            <?php echo $form->registrarse->renderViewHelper(); ?>
        </div>
    </div>
</form>
<script type="text/javascript">
    $('#content-form').validate({
        rules: {
          email: {
            required: true,
            email: true
          },
          name: {
              minlength: 3,
            required: true
          },
          password: {
              minlength: 4,
            required: true
          },
          confirmPassword: {
              minlength: 4,
            required: true
          },
        },
        highlight: function(element) {
            $(element).closest('.control-group').removeClass('success').addClass('error');
            
        },
        success: function(element) {
            $(element).text('OK!').addClass('valid')
            $(element).closest('.control-group').removeClass('error').addClass('success');
            
        }
      });
      
      jQuery('#email').tooltip({
        placement: 'right',
        title: 'Tu email es tu usuario. A él enviaremos todos los emails referidos a tus comercios.',
      });
      
      jQuery('#name').tooltip({
        placement: 'right',
        title: 'Nombre de persona física ó contacto. Es el nombre al cual se emitirán las facturas.',
      });
      
      jQuery('#cuit').tooltip({
        placement: 'right',
        title: 'Este campo se usará al momento de generar las facturas por el servicio',
      });
      
      jQuery('#password').tooltip({
        placement: 'right',
        title: 'Hasta 50 caracteres alfanuméricos.',
      });
       
      jQuery('#confirmPassword').tooltip({
        placement: 'right',
        title: 'Hasta 50 caracteres alfanuméricos. Debe ser idéntico al campo Contraseña.',
      });
</script>
