<style type=text/css>
sup{
    font-size: .6em;
}

.div_slider{
    height: 350px;
    width: 380px;
    position: absolute;
    z-index: 999;
    border: 5px solid #D9D9D9;
    border-bottom: none;
    float: none;    
}
</style>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("#div_map").click(function () {
            jQuery("#div_map").slideToggle("slow");
        });
    
        jQuery("#a_map").click(function () {
             var zoom="16";
             var size="380x350";
             var sensor="true";
             var format = "jpg";
            urlGoogleMaps = "http://maps.google.com/maps/api/staticmap?center="+jQuery("#hidden_latitude").val() + "," + jQuery("#hidden_longitude").val()
                                +"&zoom="+zoom
                                +"&size="+size
                                +"&format="+format
                                +"&markers=icon:http://dev.promosalpaso.com/images/pap_location.png|" + jQuery("#hidden_latitude").val() + "," + jQuery("#hidden_longitude").val()      // label:S%7C11211%7C11206%7C11222" 
                                +"&sensor="+sensor; 
         
         jQuery("#img_map").attr("src", urlGoogleMaps);
            jQuery("#div_map").slideToggle("slow");
        });
    })
</script>
 
<div id="promobody" class="modal hide fade" style="width: 400px;">
    <div class="modal-header" style="padding: 5px 15px;">
        <img src="/images/logo-promosalpaso70.png" style="width: 3em; height: 3em; padding: 3px;"/>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    </div>
    <div class="row-fluid" style="background-color: white; margin: 5px; width: 390px; position: absolute;">
        <div id="pbheader"class="row-fluid" style="margin-bottom: 0px; border-bottom: 2px solid grey">
            <div class="span2"><img id="det-img-comercio" src="" style="width: 3.5em; height: 3.5em; margin: 4px;" class="img-polaroid"/></div>    
            <div class="span10">
                <div class="row-fluid pagination-centered" style="margin-bottom: 0px; margin-top: 10px;">
                    <div id="det-name" class="det-comercio">Nombre Comercio</div>
                </div>
                <div class="row-fluid pagination-centered">
                    <div id="det-direccion" class="det-direccion">Av de Mayo 25448 - Ramos Mejía</div>
                </div>
            </div>
        </div>
        <div id="div_map" class="div_slider" style="display: none;">
            <img id="img_map" src=""/>
        </div>
        <div class="row-fluid">
            <div id="det-long_description" class="descripcion det-font-oscuro">Descripcion larga</div>
        </div>
        <div class="row-fluid">
            <div id="det-displayed_text" class="det-displayed_text">2X1 de Lunes a Viernes</div>
        </div>
        <div class="row-fluid" style="margin-bottom: 0px; ; padding-bottom: 5px;">
            <div class="span3">
                <img id="det-img-promo" src="/images/trebol.png" class="promo-image img-polaroid"/>
            </div>
            <div class="span8 pagination-centered">
                <div id="det-precio">
                    <div id="det-short_description" class="det-direccion">Torta de Frutillas</div>
                    <div style="text-align: center;">
                        <div id="precio_desde" class="det-desde">desde&nbsp;</div>
                        <div id="det-promo_value" class="precio" style="font-size: 2.5em; line-height: normal;">30</div>
                    </div>
                </div>
            </div>
            <div class="span1">
                <div id="det-alarma" style="background-image: url(/images/alert-icon.png); background-repeat: no-repeat; background-position: center bottom; float: right; height: 100%; min-height: 80px; width: 60px; margin: 5px;">
                    <div id="det-alarm_num" style="padding-top: 34px; font-size: 1.1em; font-weight: bold; color: white; text-align: center; height: 15px;">29</div>
                    <div id="det-alarm_type" style="font-size: 0.8em; color: white; text-align: center; height: 18px; vertical-align: top;">unid.</div>
                </div>
            </div>
            
            
        </div>
        <div class="row-fluid" style="background-color: #E6E6E6; padding-bottom: 7px; padding-top: 3px;">
            <div class="span5" style="border-right: 1px solid #FFFFFF;">
                <a id="a_map" href="#" class="ui-button" style="text-decoration: none; color: black; font-weight: bold;">
                    <div style="float: left; margin-top: 5px;">
                        <img id="det-img-mapa" src="/images/map-icon.png" class="promo-image img-polaroid"/>
                    </div>
                    <div class="det-font-oscuro det-ver-mapa">VER MAPA</div>
                </a>
            </div>
            <div class="span5">
                <a href="#" id="linkFavorite" class="ui-button" style="padding-top: 22px;">
                    <table style="width: 100%; height: 100%;">
                        <tr>
                            <td style="width: 30px; text-align: right;"><img src="/images/trebol.png" style="height: 30px; width: 30px;"/></td>
                            <td style="width: 70px; text-align: left;"><div id="favtext" style="margin: 5px; text-align: left; font-size: 1.1em; font-weight: bold; color: #42962F">Agregar a Favoritos</div></td>
                        </tr>
                    </table>
                </a>
            </div>
            <div class="span2">
                <div style="float: right; padding: 5px 5px 0 0;">
                    <div id="det-web"><a id="det-link" href="" target="new"><img src="/images/web-icon.png" style="height:27px; margin:0 0 2px;"/></a></div>
                    <div id="det-tel"><a id="det-phone" href="#"><img id="img-tel-icon" src="/images/phone-icon.png"/ style="height:27px; margin:0 0 2px;"></a></div>
                    <div id="det-email"><a id="det-msg" href="#"><img src="/images/mail-icon.png"/ style="height:27px; margin:0 0 2px;"></a></div>
                </div>
            </div>
        </div>
    </div>
</div>
<button id="btnpromobody" type="button" data-toggle="modal" data-target="#promobody" style="display: none;"/>
<input id="hidden_latitude"/>
<input id="hidden_longitude"/>

