<?php
    $messages = $this->form->getMessages();
    $this->form->setAction($this->url());
    $form = $this->form;
?>
<script type="text/javascript">
function clickFile(){
        document.getElementById("filePromo").click();
}
function sub(obj){
    var file = obj.value;
    var fileName = file.split("\\");
    document.getElementById("yourFile").innerHTML = "<p>" + fileName[fileName.length-1] + "</p>";
}
</script>
<style type="text/css">
table,th, td
{
    /*border: 1px solid black;*/
    padding: 0;
    margin: 0;
}
label[for=branches]{
    visibility: hidden;
}
</style>

<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype="multipart/form-data" class="form-horizontal">
<div class="row-fluid">
    <div class="row">
        <div class="pagination-centered" id="titulo">
            <h1>Editar Promoción</h1>
        </div>
    </div>
    <hr class="hr-subtitle"/>
    <?php echo $this->errorMessage($this->form, $messages); ?>
    <div class="row-fluid">
        <div class="span8">
            <fieldset>
                <legend><h4>Portada de Promoción</h4></legend>
                    <div class="row-fluid">
                        <div class="span10">
                            <div class="control-group">
                                <?php echo $form->displayedText->renderLabel(); ?>
                                <div class="controls">
                                    <?php echo $form->displayedText->renderViewHelper(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="span2">
                            <img src="/images/backend/goto-help.png" width="32px" onclick="loadHelp('Editar Promoción', 'tabs-promo-2');" title="Ayuda de Promociones" style="float: right;"/>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="control-group">
                            <?php echo $form->shortDescription->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->shortDescription->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span4">
                            <div class="control-group">
                                <?php echo $form->promoValue->renderLabel(); ?>
                                <div class="controls">
                                    <?php echo $form->promoValue->renderViewHelper(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="span4">
                            <div class="control-group">
                                <?php echo $form->valueType->renderLabel(); ?>
                                <div class="controls">
                                    <?php echo $form->valueType->renderViewHelper(); ?>
                                </div>
                            </div>
                         </div>
                         <div class="span4">
                            <div class="control-group">
                                <?php echo $form->valueSince->renderLabel(); ?>
                                <div class="controls">
                                    <?php echo $form->valueSince->renderViewHelper(); ?>
                                </div>
                            </div>
                         </div>
                    </div>
                </fieldset>
        </div>
        <div class="span4">
            <fieldset>
                <legend><h4>Imagen</h4></legend>
                <div class="row-fluid pagination-centered">
                     <?php echo $form->imagePromo->renderViewHelper(); ?>
                     <div id='yourFile' style="width: 100%; text-align: center; font-size: small; color: #666666;"></div>
                </div>
                <div class="row-fluid pagination-centered">
                    <button id="fakefile" class="btn btn-small" onclick="clickFile();" type="button" name="fakefile"><i class="icon-upload"></i> Cargar Imagen</button>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="row-fluid">
    <fieldset>
        <legend><h4>Detalle de Promoción</h4></legend>
        <div class="span6">
            <div class="row-fluid">
                <div class="control-group">
                    <?php echo $form->promoCode->renderLabel(); ?>
                    <div class="controls">
                        <?php echo $form->promoCode->renderViewHelper(); ?>
                    </div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="control-group">
                    <?php echo $form->promoType->renderLabel(); ?>
                    <div class="controls">
                        <?php echo $form->promoType->renderViewHelper(); ?>
                    </div>
                </div>    
            </div>
            <div class="row-fluid">
                <div class="control-group">
                    <?php echo $form->starts->renderLabel(); ?>
                    <div class="controls">
                        <?php echo $form->starts->renderViewHelper(); ?>
                    </div>
                </div>    
            </div>
            <div class="row-fluid">
                <div class="control-group">
                    <?php echo $form->ends->renderLabel(); ?>
                    <div class="controls">
                        <?php echo $form->ends->renderViewHelper(); ?>
                    </div>
                </div>    
            </div>
            <div class="row-fluid">
                <div class="control-group">
                    <?php echo $form->quantity->renderLabel(); ?>
                    <div class="controls">
                        <?php echo $form->quantity->renderViewHelper(); ?>
                    </div>
                </div>    
            </div>
            <div class="row-fluid">
                <div class="control-group">
                    <label class="control-label" for="alertType">Tipos de Alertas</label>
                    <div class="controls">
                        <?php echo $form->alertType->renderViewHelper(); ?>
                    </div>
                </div>    
            </div>
        </div>
        <div class="span5">
            <div class="row-fluid">
                <div class="control-group">
                    <?php echo $form->longDescription->renderLabel(); ?>
                    <div class="controls">
                        <?php echo $form->longDescription->renderViewHelper(); ?>
                    </div>
                </div>    
            </div>
            <div class="row-fluid">
                <div class="control-group">
                    <?php echo $form->state->renderLabel(); ?>
                    <div class="controls">
                        <?php echo $form->state->renderViewHelper(); ?>
                    </div>
                </div>    
            </div>
            <div class="row-fluid">
                <div class="control-group">
                    <?php echo $form->promoCost->renderLabel(); ?>
                    <div class="controls">
                        <?php echo $form->promoCost->renderViewHelper(); ?>
                    </div>
                </div>    
            </div>
            <div class="row-fluid">
                <div class="span10">
                    <div class="control-group">
                        <?php echo $form->visited->renderLabel(); ?>
                        <div class="controls">
                            <?php echo $form->visited->renderViewHelper(); ?>
                        </div>
                    </div>
                </div>
                <div class="span2">
                    <img src="/images/backend/goto-help.png" width="32px" onclick="loadHelp('Detalle de Promoción', 'tabs-promo-3');" title="Ayuda detalle de Promo" style="float: right;"/>    
                </div>    
            </div>
        </div>
    </fieldset>
    </div>
    <div class="row-fluid">
        <div class="span2">
            <img src="/images/backend/goto-help.png" width="32px" onclick="loadHelp('Costo de Promoción', 'tabs-costos-1');" title="Ayuda costo de Promo" style="float: right;"/>
        </div>
        <div class="span3 text-right">
            <p class="text-right"><h4>Costo total de la Promo: </h4></p>
        </div>
        <div class="span2 text-left">
            <h3>$<span id="totalPromoCost"></span></h3>
        </div>
        <div class="span5 pagination-right">
            <input id="preview" class="btn" onclick="showPreview();" value="Previsualizar"/>
            <?php echo $form->clone->renderViewHelper(); ?>&nbsp;
            <?php
                $endsdate = DateTime::createFromFormat('d-m-Y', $form->ends->getValue());
                $today = DateTime::createFromFormat('d-m-Y', date('d-m-Y'));
                if($endsdate->format('Y-m-d') >= $today->format('Y-m-d')) 
                    echo $form->save->renderViewHelper(); 
            ?>
        </div>
    </div>
</div>
    <?php 
        echo $form->filePromo;
        echo $form->promoId;
        echo $form->userId;
        echo $form->userInfo;
        echo $form->branches;
        echo $form->availableStartDate;
        echo $form->dateAsNew;
    ?>
</form>
<script>
 $(document).ready(function(){
   $("#starts").datepicker({
      showOn: 'both',
      buttonImage: '/images/calendar-icon.png',
      buttonImageOnly: true,
      changeYear: false,
      minDate: 0,
      numberOfMonths: 1,
      onSelect: function(textoFecha, objDatepicker){
        var dateParts = textoFecha.split("-");
        var dateSelected = new Date(dateParts[2], (dateParts[1] - 1), dateParts[0]);
        if(dateSelected > $("#ends").datepicker('getDate'))
            $("#ends").datepicker('setDate', dateSelected);
        $("#ends").datepicker('option', 'minDate', $("#starts").datepicker('getDate'));
        showPromoTotalCost();   
      }
   });
   if($("#starts").val() == "")
        $("#starts").datepicker( "setDate", new Date() );
   
   $("#ends").datepicker({
      showOn: 'both',
      buttonImage: '/images/calendar-icon.png',
      buttonImageOnly: true,
      changeYear: false,
      minDate: 0,
      numberOfMonths: 1,
      onSelect: function(textoFecha, objDatepicker){
         showPromoTotalCost();
      }
   });
   
   var today = new Date();
   var kickoff = parseStringToDate(jQuery('#availableStartDate').val());
   
   if(kickoff > today){
       $("#starts").datepicker('option', 'minDate', kickoff);
       $("#ends").datepicker('option', 'minDate', kickoff);
   }
   
   if(jQuery("#starts").val() == "")
        jQuery("#ends").datepicker( "setDate", new Date() );
   if(jQuery("#starts").datepicker("getDate") < getToday())
        jQuery("#starts").datepicker("disable"); 
        //jQuery("#starts").datepicker({minDate:-1,maxDate:-2}).attr('readonly','readonly');
   
   showPromoTotalCost(); 
})
 
 function showPreview(){
     var data;
     data = collectPromotionFormData();
     FillPromotion(data.promotion[0]);
 }
 
 $("form").submit(function() {
    $("#starts").removeAttr("disabled", "disabled");
});

    $("#displayedText").charCount({
        allowed: 25,        
        warning: 20,
    });
    
    $("#shortDescription").charCount({
        allowed: 60,        
        warning: 50,
    }); 

 </script>
<?php echo $this->partial("promotion/_promobody.phtml");?>
<?php echo $this->partial("index/_contextual-help.phtml");?>
<script type="text/javascript" src="/scripts/tooltips-promos.js"></script>