<!-- <script type="text/javascript" src="/scripts/jquery-1.8.2.js"></script>
<script type="text/javascript" src="/scripts/jquery-ui-1.9.1.custom.min.js"></script>
<script type="text/javascript" src="/scripts/backend.js"></script>
-->
<?php
    $messages = $this->form->getMessages();
    $this->form->setAction($this->url());
    $form = $this->form;
?>
<script type="text/javascript">
function clickFile(){
        document.getElementById("filePromo").click();
}
function sub(obj){
    var file = obj.value;
    var fileName = file.split("\\");
    document.getElementById("yourFile").innerHTML = "<p>" + fileName[fileName.length-1] + "</p>";
}
</script>
<style type="text/css">
table,th, td
{
    /*border: 1px solid black;*/
    padding: 0;
    margin: 0;
}
label[for=branches]{
    visibility: hidden;
}
</style>

<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype="multipart/form-data" class="form-horizontal">
<div class="row-fluid">
    <div class="row">
        <div class="pagination-centered" id="titulo">
            <h1>Editar Promoción</h1>
        </div>
    </div>
    <hr class="hr-subtitle"/>
    <?php echo $this->errorMessage($this->form, $messages); ?>
    <div class="row-fluid">
        <div class="span8">
            <fieldset>
                <legend>Portada de Promoción</legend>
                    <div class="row-fluid">
                        <div class="control-group">
                            <?php echo $form->displayedText->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->displayedText->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="control-group">
                            <?php echo $form->shortDescription->renderLabel(); ?>
                            <div class="controls">
                                <?php echo $form->shortDescription->renderViewHelper(); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span2">
                            <div class="control-group">
                                <?php echo $form->promoValue->renderLabel(); ?>
                                <div class="controls">
                                    <?php echo $form->promoValue->renderViewHelper(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="span2">
                            <div class="control-group">
                                <?php echo $form->valueSince->renderLabel(); ?>
                                <div class="controls">
                                    <?php echo $form->valueSince->renderViewHelper(); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
        </div>
        <div class="span4">
            <fieldset>
                        <legend>Imagen</legend>
                        <table width="100%">
                            <tr>
                                <td style="text-align: center;">
                                    <?php echo $form->imagePromo->renderViewHelper(); ?>
                                    <img src="/images/backend/icon-info.gif" title="Descripción de la descripción." />
                                </td>
                                <td style="text-align: center;">
                                    <?php echo $form->fakefile->renderViewHelper(); ?>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <div id='yourFile' style="width: 100%; text-align: center;"><p>Imagen por defecto</p></div>
                                </td>
                            </tr>
                        </table>
                    </fieldset>
        </div>
    </div>
</div>    
    <div align="center">
        <table width="95%">
            <tr>
                <td>
                    
                </td>
                <td>
                    
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <fieldset>
                        <legend>Detalle de Promoción</legend>
                        <table width="100%">
                            <tr>
                                <td><?php echo $form->promoCode->renderLabel(); ?></td>
                                <td><?php echo $form->promoCode->renderViewHelper(); ?></td>
                                <td><?php echo $form->longDescription->renderLabel(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->promoType->renderLabel(); ?></td>
                                <td><?php echo $form->promoType->renderViewHelper(); ?></td>
                                <td rowspan="3"><?php echo $form->longDescription->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->starts->renderLabel(); ?></td>
                                <td><?php echo $form->starts->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->ends->renderLabel(); ?></td>
                                <td><?php echo $form->ends->renderViewHelper(); ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $form->quantity->renderLabel(); ?></td>
                                <td><?php echo $form->quantity->renderViewHelper(); ?></td>
                                <td>
                                    <table>
                                        <tr>
                                            <td><?php echo $form->state->renderLabel(); ?></td>
                                            <td><?php echo $form->state->renderViewHelper(); ?></td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td rowspan="2"><?php echo $form->alertType->renderLabel(); ?></td>
                                <td rowspan="2"><?php echo $form->alertType->renderViewHelper(); ?></td>
                                <td>
                                    <table>
                                        <tr>
                                            <td><?php echo $form->promoCost->renderLabel(); ?></td>
                                            <td><?php echo $form->promoCost->renderViewHelper(); ?></td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <table>
                                        <tr>
                                            <td><?php echo $form->visited->renderLabel(); ?></td>
                                            <td><?php echo $form->visited->renderViewHelper(); ?></td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </fieldset>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div><span>Costo de la Promo: $</span><span id="promoCost"></span></div>
                </td>
            </tr>
            <tr>
                <td align="right" colspan="2">
                    <?php echo $form->save->renderViewHelper(); ?>
                </td>
            </tr>
        </table>
    </div>
    <?php 
        echo $form->filePromo;
        echo $form->promoId;
        echo $form->userId;
        echo $form->branches;
    ?>
</form>
<script>
  $(document).ready(function() {
    $("#starts").datepicker({ dateFormat: "dd-mm-yy" });
  });
  $(document).ready(function() {
    $("#ends").datepicker({ dateFormat: "dd-mm-yy" });
  });
 </script>