<?php
    $messages = $this->errorMessage;
      /*echo $this->headLink()->appendStylesheet($this->baseUrl().'/skins/default/css/jquery-ui-1.8.23.custom.css')
            ->appendStylesheet($this->baseUrl().'/skins/default/css/ui.jqgrid.css');
      echo $this->headScript()->appendScript($this->baseUrl().'/scripts/jquery-1.8.0.min.js')
            ->appendScript($this->baseUrl().'/scripts/jquery-ui-1.8.23.custom.min.js')
            ->appendScript($this->baseUrl().'scripts/grid.locale-es.js')
            ->appendScript($this->baseUrl().'/scripts/jquery.jqGrid.min.js');
      */
?>
<script type="text/javascript" src='/scripts/grid.locale-es.js'></script>
<script type="text/javascript" src='/scripts/jquery.jqGrid.min.js'></script>
<script type="text/javascript" src="/scripts/promosalpaso.js"></script>
    <div class="row">
        <div class="pagination-centered" id="titulo">
            <h1>Mis Promociones</h1>
        </div>
    </div>
    <hr class="hr-subtitle"/>
    <?php echo $this->errorMessage($this->form, $messages); ?>
    <?php echo $this->partial("index/_alert.phtml"); ?>
<div class="row-fluid">
    <div class="span2 pagination-centered">
        <h4 style="margin-top: 0;">Publicaciones Activas</h4>
    </div>
    <div class="span3" style="margin-bottom: 10px;">
        <?php if(count($this->currentInfo) > 0){
            echo "<div>";
            echo "<p class='textinfo'><b>Cantidad: </b><b><span style='font-size: 17.5px; color: #FF6A15'>".$this->cant_activas."</b></span></p>";
            echo "<p class='textinfo'><b>Distribución de promociones:</b><p>";
                foreach($this->currentInfo as $distri_info){
                    echo "<p class='textinfo'  style='margin:10px;'>".$distri_info["cant"]." promo/s de costo $".$distri_info["promo_cost"]." con ".$distri_info["visited"]." visitas.</p>";        
                }   
            }
            else{
                echo "<p>No tienes promos activas en este momento. ¿Qué esperas para dar a conocer tus promos?.<p>";
            }
            echo "</div>"; 
        ?>
    </div>
    <div class="span2 pagination-centered">
        <h4 style="margin-top: 0;">Histórico Publicaciones </h4>
    </div>
    <div class="span3" style="margin-bottom: 10px;">
        <?php if(count($this->historicalInfo) > 0){
            echo "<div>";
            echo "<p class='textinfo'><b>Cantidad: </b><b><span style='font-size: 17.5px; color: #FF6A15'>".$this->cant_historical."</b></span></p>";
            echo "<p class='textinfo'><b>Distribución de promociones:</b><p>";
                foreach($this->historicalInfo as $distri_info){
                    echo "<p class='textinfo'  style='margin:10px;'>".$distri_info["cant"]." promo/s de costo $".$distri_info["promo_cost"]." con ".$distri_info["visited"]." visitas.</p>";        
                }   
            }
            else{
                echo "<p>No tienes promos activas en este momento. ¿Qué esperas para dar a conocer tus promos?.<p>";
            }
            echo "</div>"; 
        ?>
    </div>
    <div class="span1">
        <?php echo $this->partial("promotion/_botonera.phtml"); ?>
    </div>
    <div id="div_grid_container" class="row-fluid pagination-centered">
            <table width="100%">
                <tr><td align="center">
                    <table id="list2"></table>
                    <div id="pager2"></div>
                </td></tr>
            </table>
        </br>
        </br>
    </div>
    <div class="row-fluid pagination-centered">
        <?php echo $this->partial("promotion/_botonera.phtml"); ?> 
    </div>
</div>
<script type="text/javascript">
    jQuery("#list2").jqGrid({url:_baseUri + 'promotion/datos',datatype: "json",
         colNames:['Acción', 'Código','Inicio', 'Fin', 'Descripción', 'Valor', 'Estado', 'Visitas', ''],
         colModel:[ {name:'act',index:'act', width:50,sortable:false},
                    {name:'Código',index:'promo_code', width:95}, 
                    {name:'Inicio',index:'starts', width:95, align: 'center'},
                    {name:'Fin',index:'ends', width:95, align: 'center'},
                    {name:'Descripción',index:'short_description', width:450},
                    {name:'value',index:'promo_value', width:70, align: 'center'},
                    {name:'Estado',index:'state', width:50, align: 'center'},
                    {name:'Visitas',index:'visited', width:50, align: 'center'},
                    {name:'is_percentage',index:'is_percentage', hidden: true},
         ],
         rowNum:20,
         rowList:[20,30,40],
         pager: '#pager2',
         sortname: 'starts',
         viewrecords: true,
         sortorder: "desc",
         mtype:"POST",
         autowidth: true,
         height: "300px",
         caption:"Promociones",
         gridComplete: function(){
            var ids = jQuery("#list2").jqGrid('getDataIDs');
            if(ids.length == 0 ){
                     showMessage("info", "Aún no tienes promociones cargadas.");
                     jQuery("#gbox_list2").hide();
                     return;
                 }
            for(var i=0;i < ids.length;i++){
                var cl = ids[i];
                var today = new Date();
                var row = jQuery("#list2").jqGrid('getRowData',cl);
                var _data_row = jQuery("#list2").getRowData(cl).Inicio.split("/");
                var start = new Date(_data_row[2], parseInt(_data_row[1])-1, _data_row[0]);       
                _data_row = jQuery("#list2").getRowData(cl).Fin.split("/");
                var end = new Date(_data_row[2], parseInt(_data_row[1])-1, _data_row[0]);
                end.setDate(start.getDate()+ 1);
                
                be = "<div style='float:left; display: inline;'><a href='/promotion/edit/id/"+cl+"'><span class='ui-icon ui-icon-pencil'></span></a></div>";
                
                if(start <= today)
                    se = "";
                else 
                    se = "<div style='float:left;'><a href='/promotion/delete/id/"+cl+"'><span class='ui-icon ui-icon-trash'></span></a></div>"; 
                val = (row["is_percentage"] == "1")?cutDecimals(row["value"])+"%":"$"+cutDecimals(row["value"]);
                jQuery("#list2").jqGrid('setRowData',ids[i],{act:be+se,value:val});
            }    
    },
     })
     //jQuery("#list2").jqGrid('GridNav','#pager2',{edit:false,add:false,del:false});
     
     $(window).bind('resize', function() {
        //$('#list2').setGridWidth(width, true); //Back to original width
        $('#list2').setGridWidth($('#div_grid_container').width(), true); //Resized to new width as per window
     }).trigger('resize');
</script>
 