<?php
      /*echo $this->headLink()->appendStylesheet($this->baseUrl().'/skins/default/css/jquery-ui-1.8.23.custom.css')
            ->appendStylesheet($this->baseUrl().'/skins/default/css/ui.jqgrid.css');
      echo $this->headScript()->appendScript($this->baseUrl().'/scripts/jquery-1.8.0.min.js')
            ->appendScript($this->baseUrl().'/scripts/jquery-ui-1.8.23.custom.min.js')
            ->appendScript($this->baseUrl().'scripts/grid.locale-es.js')
            ->appendScript($this->baseUrl().'/scripts/jquery.jqGrid.min.js');
      */
?>
<div align="center">
    <div style="background-image: url(/images/backend/tit-promociones.png); background-repeat:no-repeat; background-position: center; height: 50px;">&nbsp;</div>
    <div>
        <table id="list2"></table>
        <div id="pager2"></div>
    </div>
    <div>
    <?php 
        echo $this->partial("promotion/_botonera.phtml"); 
    ?> 
    </div>
 </div>
 
<script type="text/javascript" src='/scripts/jquery-1.8.2.js'></script>
<script type="text/javascript" src='/scripts/jquery-ui-1.9.0.custom.min.js'></script>
<script type="text/javascript" src='/scripts/grid.locale-es.js'></script>
<script type="text/javascript" src='/scripts/jquery.jqGrid.min.js'></script>
<script type="text/javascript">
    jQuery("#list2").jqGrid({url:'http://promosalpaso.local/promotion/datos',datatype: "json",
         colNames:['Acción', 'Código','Inicio', 'Fin', 'Descripción', 'Valor', 'Estado', 'Visitas'],
         colModel:[ {name:'act',index:'act', width:50,sortable:false},
                    {name:'Código',index:'promo_code', width:50}, 
                    {name:'Inicio',index:'starts', width:50},
                    {name:'Fin',index:'ends', width:50},
                    {name:'Descripción',index:'short_description', width:200},
                    {name:'Valor',index:'promo_value', width:50},
                    {name:'Estado',index:'state', width:50},
                    {name:'Visitas',index:'visited', width:50},
         ],
         rowNum:10,
         rowList:[10,20,30],
         pager: '#pager2',
         sortname: 'starts',
         viewrecords: true,
         sortorder: "desc",
         mtype:"POST",
         caption:"Grilla de Promociones",
         gridComplete: function(){
            var ids = jQuery("#list2").jqGrid('getDataIDs');
            for(var i=0;i < ids.length;i++){
                var cl = ids[i];
                be = "<a href='/promotion/edit/id/"+cl+"'><span class='ui-icon ui-icon-pencil'></span></a>"; 
                se = "<a href='/promotion/delete/id/"+cl+"'><span class='ui-icon ui-icon-trash'></span></a>"; 
                jQuery("#list2").jqGrid('setRowData',ids[i],{act:be+se});
            }    
    },
     })
     //$("#list2").jqGrid('navGrid','#pager2',{edit:false,add:false,del:false});
</script>
 