<script type="text/javascript" src="/scripts/jquery-1.8.0.min.js"></script>
<script type="text/javascript" src="/scripts/jquery-ui-1.8.23.custom.min.js"></script>

<?php
      echo $this->headLink()->appendStylesheet($this->baseUrl().'/skins/default/css/jquery-ui-1.8.23.custom.css');
      //echo $this->headScript()->appendScript($this->baseUrl().'/scripts/jquery-1.8.0.min.js')
      //                          ->appendScript($this->baseUrl().'/scripts/jquery-ui-1.8.23.custom.min.js');
?>
<?php
    if(isset($this->errorMessage)){
        echo $this->errorMessage;
    }
?>
<?
    $this->form->setAction($this->url());
    echo $this->form;
?>
<script>
  $(document).ready(function() {
    $(".datepicker").datepicker();
  });
 </script>
<div id="dateStarts" class="datepicker"></div>
<div id="dateEnds" class="datepicker"></div>