<script type="text/javascript" src="/scripts/jquery-1.8.2.js"></script>
<script type="text/javascript" src="/scripts/jquery-ui-1.9.1.min.js"></script>

<?php
      //echo $this->headLink()->appendStylesheet($this->baseUrl().'/skins/default/css/jquery-ui-1.9.1.custom.css');
      //echo $this->headScript()->appendScript($this->baseUrl().'/scripts/jquery-1.8.0.min.js')
      //                          ->appendScript($this->baseUrl().'/scripts/jquery-ui-1.8.23.custom.min.js');
?>
<?php
    if(isset($this->errorMessage)){
        echo $this->errorMessage;
    }
?>
<?
    $this->form->setAction($this->url());
    echo $this->form;
    $form = $this->form;
?>
<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype="multipart/form-data">
    <div align="center">
        <table width="95%">
            <tr>
                    <td colspan="2" align="center" valign="middle" height="65px">
                        <div style="background-image: url(/images/backend/tit-promocion.png); background-repeat:no-repeat; background-position: center; height: 50px; width: 100%">&nbsp;</div>
                    </td>
                </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </table>
    </div>
</form>

<script>
  $(document).ready(function() {
    $(".datepicker").datepicker();
  });
 </script>
<div id="dateStarts" class="datepicker"></div>
<div id="dateEnds" class="datepicker"></div>