<?php
    $messages = $this->errorMessage;
    $this->form->setAction($this->url());
    $form = $this->form;
?>
<script type="text/javascript" src="/scripts/prototype.js"></script>
<script type="text/javascript" src='/scripts/grid.locale-es.js'></script>
<script type="text/javascript" src='/scripts/jquery.jqGrid.min.js'></script>
<script type="text/javascript" src="/scripts/promosalpaso.js"></script>
<script type="text/javascript">
function loadCities()
{
        var selectedValue = document.getElementById('province').options[document.getElementById('province').selectedIndex].value;
        var myAjax = new Ajax.Request(
        "<?=$this->url(array('controller'=>'Backendajax','action'=>'getCities'))?>",
            {
                method:'get',
                parameters: {province_id: selectedValue},
                onSuccess: FillForm
        });
 
}

function loadProvinces()
{       var myAjax = new Ajax.Request(
        "<?=$this->url(array('controller'=>'Backendajax','action'=>'getprovinces'))?>",
            {
                method:'get',
                onSuccess: FillFormProvinces
        });
        
 
}

function FillForm(data)
{       var select = document.getElementById("city");
        select.options.length = 0;
        var cities = eval('(' + data.responseText + ')');
        for (var i = 0; i < cities.length; i++){
            select.options[select.options.length] = new Option(cities[i].name, cities[i].city_id); 
        } 
}

function FillFormProvinces(data)
{       var select = document.getElementById("province");
        select.options.length = 0;
        var provinces = eval('(' + data.responseText + ')');
        for (var i = 0; i < provinces.length; i++){
            select.options[select.options.length] = new Option(provinces[i].name, provinces[i].province_id); 
        }
        
        loadCities(); 
}
</script>
<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype="multipart/form-data">
    <div class="row-fluid">
        <div class="row">
            <div class="pagination-centered" id="titulo">
                <h1>Búsqueda de Promociones</h1>
            </div>
        </div>
        <hr class="hr-subtitle"/>
        <?php echo $this->errorMessage($this->form, $messages); ?>
        <?php echo $this->partial("index/_alert.phtml"); ?>
    </div>
        <div class="row-fluid">
            <div class="span3 well">
                <div class="row-fluid pagination-left">
                    <span>Filtros</span>
                </div>
                <div class="row-fluid pagination-left">
                    <div class="control-group">
                        <?php echo $form->province->renderLabel(); ?>
                        <div class="controls">
                            <?php echo $form->province->renderViewHelper(); ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <?php echo $form->city->renderLabel(); ?>
                        <div class="controls">
                            <?php echo $form->city->renderViewHelper(); ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <?php echo $form->category->renderLabel(); ?>
                        <div class="controls">
                            <?php echo $form->category->renderViewHelper(); ?>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <?php echo $form->search->renderViewHelper(); ?> 
                    </div>
                </div>
            </div>
            <div class="span9 pagination-centered">
                <table id="list2"></table>
                <div id="pager2"></div>    
            </div>
        </div>
    
</form>
<script type="text/javascript">

loadProvinces();

var firstClick = true;
function getPromotions(){
    
    var city = document.getElementById('city').options[document.getElementById('city').selectedIndex].value;
    var categories = document.getElementById('category').options;
    var categoriesString = '';
    for (x=0; x<categories.length; x++){
      if(categories[x].selected)
        categoriesString += categories[x].value + ",";   
    }
    if(categoriesString != '')
        categoriesString = categoriesString.substring(0, categoriesString.length-1);
    var _url = _baseUri + '/promotion/search/city/' + city + '/categories/' + categoriesString;
    if (!firstClick){
        jQuery("#list2").jqGrid('setGridParam', { url: _url }).trigger("reloadGrid");
    }
    else{
        firstClick = false;
        
        jQuery("#list2").jqGrid({url: _url, datatype: "json",
             colNames:['Imagen', 'Comercio','Promoción', 'Dirección', 'Precio'],
             colModel:[ {name:'img',index:'path', width:50,sortable:false},
                        {name:'Comercio',index:'name', width:150}, 
                        {name:'Promoción',index:'displayed_text', width:200},
                        {name:'Dirección',index:'short_description', width:250},
                        {name:'Valor',index:'promo_value', width:45},
                        /*{name:'Mts.',index:'distance', width:30},*/
             ],
             rowNum:5,
             rowList:[10,20,30],
             pager: '#pager2',
             sortname: 'starts',
             viewrecords: true,
             sortorder: "desc",
             height: "287px",
             mtype:"POST",
             caption:"Promociones",
             gridComplete: function(){
             var ids = jQuery("#list2").jqGrid('getDataIDs');
             for(var i=0;i < ids.length;i++){
                 var cl = ids[i];
                 var row = jQuery("#list2").jqGrid('getRowData',cl); 
                 be = "<img src='/"+row["img"]+"' height='50px' width='50px' onClick='loadPromotion("+cl+")'/>"; //"<a href='/promotion/edit/id/"+cl+"'><span class='ui-icon ui-icon-pencil'></span></a>"; 
                 jQuery("#list2").jqGrid('setRowData',ids[i],{img:be});
             }
         }
        })
     //jQuery("#list2").trigger('reloadGrid');
     //jQuery("#list2").jqGrid('GridNav','#pager2',{edit:false,add:false,del:false});
    }
}

function loadPromotion(promotion_id){
    var myAjax = new Ajax.Request(
        "<?=$this->url(array('controller'=>'Backendajax','action'=>'getPromotion'))?>",
            {
                method:'get',
                parameters: {promotion_id: promotion_id},
                onSuccess: FillPromotion
        });    
}

function FillPromotion(data){
    var promotion = eval('(' + data.responseText + ')');
    alert(data.responseText);    
}
</script>