<?php
    $messages = $this->errorMessage;
      /*echo $this->headLink()->appendStylesheet($this->baseUrl().'/skins/default/css/jquery-ui-1.8.23.custom.css')
            ->appendStylesheet($this->baseUrl().'/skins/default/css/ui.jqgrid.css');
      echo $this->headScript()->appendScript($this->baseUrl().'/scripts/jquery-1.8.0.min.js')
            ->appendScript($this->baseUrl().'/scripts/jquery-ui-1.8.23.custom.min.js')
            ->appendScript($this->baseUrl().'scripts/grid.locale-es.js')
            ->appendScript($this->baseUrl().'/scripts/jquery.jqGrid.min.js');
      */
?>
<script type="text/javascript">
function loadCities()
{
        var selectedValue = document.getElementById('province').options[document.getElementById('province').selectedIndex].value;
        var myAjax = new Ajax.Request(
        "<?=$this->url(array('controller'=>'backendAjax','action'=>'getCities'))?>",
            {
                method:'get',
                parameters: {province_id: selectedValue},
                onSuccess: FillForm
        });
 
}

function FillForm(data)
{
        var select = document.getElementById("city");
        select.options.length = 0;
        var cities = eval('(' + data.responseText + ')');
        for (var i = 0; i < cities.length; i++){
            select.options[select.options.length] = new Option(cities[i].name, cities[i].city_id); 
        } 
}
</script>
<div align="center">
    <table width="100%">
        <tr>
            <td>
                <div style="background-image: url(/images/backend/tit-busqueda.png); background-repeat:no-repeat; background-position: center; height: 50px;">&nbsp;</div>
                <hr/>
                <?php echo $this->errorMessage($this->form, $messages); ?>
            </td>
        </tr>
        <tr>
            <td align="center">
                <div>
                    <table id="list2"></table>
                    <div id="pager2"></div>
                </div>
            </td>
        </tr>
        <tr>
            <td align="center" height="75px">
                <div>
                    <?php echo $this->partial("promotion/_botonera.phtml"); ?> 
                </div>        
            </td>
        </tr>
    </table>
 </div>