<div class="navbar navbar-fixed-bottom">
    <div class="navbar-inner">
        <div class="container">
            <div class="pull-left" style="height:40px; line-height:40px;">
                <p>Promos al Paso es una marca registrada.</p>
            </div>
            <div class="pull-right" style="height:40px; line-height:40px;">
                <span>Podés seguirnos en </span><a href="https://www.facebook.com/promos.al.paso" target="_blanck"><img alt="Facebook" src="/images/backend/facebook.png" height="28" width="28" /></a>&nbsp;<a href="https://twitter.com/promosalpaso" target="_blank"><img alt="Twitter" src="/images/backend/twitter.png" height="28" width="28"/></a>
            </div>
        </div>
    </div>
</div>