<div class="navbar navbar-fixed-bottom">
    <div class="navbar-inner">
        <div class="container" style="display: table;">
            <div class="pull-left" style="height:40px; line-height:40px; display: table-cell;">
                <span>Promos al Paso es una marca registrada.</span>
                <span><a href="<?php echo $this->url(array('controller'=>'index','action'=>'conditions'));?>">Términos y condiciones</a></span>
            </div>
            <div class="pull-right" style="height:40px; line-height:40px; display: table-cell;">
                <span>Podés seguirnos en </span><a href="https://www.facebook.com/PromosAlPaso" target="_blanck"><img alt="Facebook" src="/images/backend/facebook.png" height="28" width="28" /></a>&nbsp;<a href="https://twitter.com/promosalpaso" target="_blank"><img alt="Twitter" src="/images/backend/twitter.png" height="28" width="28"/></a>
            </div>
        </div>
    </div>
</div>