<div style="background: url(/skins/default/css/images/ui-bg_inset-hard_50_fa6400_1x100.png)">
    <table width="100%" style="background-color: inherit;">
        <tr>
            <td align="right"> <div style="background-image: url(/images/backend/logo-promosalpaso70.png); 
                       background-repeat:no-repeat; 
                       background-position: center right; 
                       width: 100%; 
                       height: 90px;
                       background-color: inherit;">&nbsp;</div>
            </td>
            <td align="center">
                <div id="header" style="width: 100%; height: 90px; background-image: url(/images/backend/tit-promosalpaso.png); background-repeat:no-repeat; background-position: center center; background-color: transparent;">
            </td>
            <td align="left"> <div style="background-image: url(/images/backend/logo-promosalpaso70.png); 
                       background-repeat:no-repeat; 
                       background-position: center left; 
                       width: 100%; 
                       height: 90px;
                       background-color: inherit;">&nbsp;</div>
            </td>
        </tr>
    </table>
</div>
