<style id="bsa_css" type="text/css">
    .one{position:relative}
    .one .bsa_it_ad{display:block;padding:15px;border:1px solid #e1e1e1;background:#f9f9f9;font-family:helvetica,arial,sans-serif;line-height:100%;position:relative}
    .one .bsa_it_ad a{text-decoration:none}
    .one .bsa_it_ad a:hover{text-decoration:none}
    .one .bsa_it_ad .bsa_it_t{display:block;font-size:12px;font-weight:bold;color:#212121;line-height:125%;padding:0 0 5px 0}
    .one .bsa_it_ad .bsa_it_d{display:block;font-size:11px;color:#434343;font-size:12px;line-height:135%}
    .one .bsa_it_ad .bsa_it_i{float:left;margin:0 15px 10px 0}
    .one .bsa_it_p{display:block;text-align:right;position:absolute;bottom:10px;right:15px}
    .one .bsa_it_p a{font-size:10px;color:#666;text-decoration:none}
    .one .bsa_it_ad .bsa_it_p a:hover{font-style:italic}
</style>
<div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <a class="brand" href="http://promosalpaso.com/">Promos al Paso</a>
       <div class="nav-collapse collapse" id="main-menu">
        <ul class="nav" id="main-menu-left">
          <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>" id="tab_home">Inicio</a></li>
          <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'news'));?>" id="tab_news">Noticias</a></li>
          <li><a href="<?php echo $this->url(array('controller'=>'promotion','action'=>'search'));?>" id="tab_search">Buscar Promos</a></li>
          <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'contact'));?>" id="tab_contact">Contacto</a></li>
        </ul>
        <ul class="nav pull-right" id="main-menu-right">
          <li><?php echo $this->profileLink(); ?></li>
        </ul>
       </div>
     </div>
   </div>
 </div>
 <div class="container">
     <header class="jumbotron subhead" id="overview">
          <div class="row">
            <div class="span6">
              <h1>Promos al Paso</h1>
              <p class="lead">Todas las promos en la palma de tu mano.</p>
            </div>
            <div class="span6">
              <div class="bsa well">
                  <div id="bsap_1277971" class="bsap_1277971 bsap">
                    <div class="bsa_it one">
                        <div class="bsa_it_ad ad1 odd" id="bsa_2771088" style="padding: 10px;">
                            <span class="bsa_it_i"><img src="/images/backend/logo-promosalpaso.png" width="80px" height="80px" alt="Promos al Paso"></span>
                            <span class="bsa_it_d" style="text-align: center;">Una nueva y simple plataforma de anuncios. <br/>Registrar tu negocio es gratis.</span>
                        </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
    </header>
</div>