<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php
        echo $this->headTitle();
        echo $this->headScript();
        // add a link to the site style sheet
        //$this->headLink()->appendStylesheet('/css/masterlayout.css');
        $this->loadSkin($this->skin);
        echo $this->headLink();
?>
<script type="text/javascript" src="/scripts/jquery-1.8.2.js"></script>
<script type="text/javascript" src="/scripts/jquery-ui-1.9.2.custom.js"></script>
<script type="text/javascript" src="/scripts/bootstrap.js"></script>
<script type="text/javascript" src="/scripts/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="/scripts/bootswatch.js"></script>
<script type="text/javascript" src="/scripts/bootbox.js"></script>
<script type="text/javascript" src="/scripts/jquery.validate.js"></script>
<script type="text/javascript" src="/scripts/environment.js"></script>
<script type="text/javascript" src="/scripts/backend.js"></script>
</head>
<body>
    <div id="pageWrapper">
        <?php echo $this->partial("_header.phtml"); ?>    
        
        <div id="content" class="container">
            <div id="main_menu">
                <?php echo $this->layout()->menu; ?>
            </div>
            <div id="main" class="well">
                <?php echo $this->layout()->content;?>&nbsp;
            </div>
        </div>
        <?php echo $this->partial("_footer.phtml"); ?>
    </div>
</body>
</html>