<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php
        echo $this->headTitle();
        echo $this->headScript();
        // add a link to the site style sheet
        //$this->headLink()->appendStylesheet('/css/masterlayout.css');
        $this->loadSkin($this->skin);
        echo $this->headLink();
?>
<script type="text/javascript">
    var _baseUri = "http://promosalpaso.local/";
    //var _baseUri = "http://dev.promosalpaso.com/";
</script>
</head>
<body>
    <div id="pageWrapper">
        <?php echo $this->partial("_header.phtml"); ?>    
        <div id="sidebar">
            <div id="subNav" style="background-color: inherit;">
                <?php echo $this->layout()->menu; ?>
            </div>
        </div>
        <div id="main">
            <?php echo $this->layout()->content;?>&nbsp;
        </div>
        <?php echo $this->partial("_footer.phtml"); ?>
    </div>
</body>
</html>