<div class="row-fluid">
    <div class="row">
        <div class="pagination-centered" id="titulo">
            <h1>A ocurrido un error!!</h1>
        </div>
    </div>
    <hr class="hr-subtitle"/>
    <div class="row">
        <h3>Exception information:</h3>
        <p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>
    </div>
    <?php if (isset($this->exception)): ?>
    <div class="row">
        <h3>Stack trace:</h3>
        <pre><?php echo $this->exception->getTraceAsString() ?></pre>

        <h3>Request Parameters:</h3>
        <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>  
    </div>
  
  

  <?php endif ?>
